// GENERATED by src/tools/map_ihris5.py from src/ihris-4-on-fhir/mapping/crosswalk.json. Do not edit: change the source or the generator.

Instance: Demographic-to-ihris5-ig
InstanceOf: StructureMap
Usage: #definition
* id = "Demographic-to-ihris5-ig"
* url = "https://litlfred.github.io/ihris/dak/StructureMap/Demographic-to-ihris5-ig"
* version = "4.3.3"
* name = "DemographicToIhris5Ig"
* title = "iHRIS 4 Demographic to iHRIS 5 IhrisTestPractitioner (ig)"
* status = #draft
* description = "GENERATED from src/ihris-4-on-fhir/mapping/crosswalk.json: only the exact (and owner-accepted) element matches, by label equality. Values the target profile fixes (such as Basic.code) are not set here. iHRIS 5 is referenced by canonical only; it is not an IG dependency (D5)."
* structure[0].url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Demographic"
* structure[0].mode = #source
* structure[0].alias = "Demographic"
* structure[1].url = "http://ihris.org/fhir/StructureDefinition/ihris-test-practitioner"
* structure[1].mode = #target
* structure[1].alias = "IhrisTestPractitioner"
* group[0].name = "Demographic"
* group[0].typeMode = #none
* group[0].input[0].name = "src"
* group[0].input[0].type = "Demographic"
* group[0].input[0].mode = #source
* group[0].input[1].name = "tgt"
* group[0].input[1].type = "IhrisTestPractitioner"
* group[0].input[1].mode = #target
* group[0].rule[0].name = "birthDate"
* group[0].rule[0].source[0].context = "src"
* group[0].rule[0].source[0].element = "birthDate"
* group[0].rule[0].source[0].variable = "s1"
* group[0].rule[0].target[0].context = "tgt"
* group[0].rule[0].target[0].element = "birthDate"
* group[0].rule[0].target[0].transform = #copy
* group[0].rule[0].target[0].parameter[0].valueId = "s1"
