// GENERATED by src/tools/map_ihris5.py from src/ihris-4-on-fhir/mapping/crosswalk.json. Do not edit: change the source or the generator.

Instance: Deployment-to-ihris5-qualify
InstanceOf: StructureMap
Usage: #definition
* id = "Deployment-to-ihris5-qualify"
* url = "https://litlfred.github.io/ihris/dak/StructureMap/Deployment-to-ihris5-qualify"
* version = "4.3.3"
* name = "DeploymentToIhris5Qualify"
* title = "iHRIS 4 Deployment to iHRIS 5 IhrisBasicDeployment (qualify)"
* status = #draft
* description = "GENERATED from src/ihris-4-on-fhir/mapping/crosswalk.json: only the exact (and owner-accepted) element matches, by label equality. Values the target profile fixes (such as Basic.code) are not set here. iHRIS 5 is referenced by canonical only; it is not an IG dependency (D5)."
* structure[0].url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Deployment"
* structure[0].mode = #source
* structure[0].alias = "Deployment"
* structure[1].url = "http://ihris.org/fhir/StructureDefinition/ihris-basic-deployment"
* structure[1].mode = #target
* structure[1].alias = "IhrisBasicDeployment"
* group[0].name = "Deployment"
* group[0].typeMode = #none
* group[0].input[0].name = "src"
* group[0].input[0].type = "Deployment"
* group[0].input[0].mode = #source
* group[0].input[1].name = "tgt"
* group[0].input[1].type = "IhrisBasicDeployment"
* group[0].input[1].mode = #target
* group[0].rule[0].name = "extension-deployment"
* group[0].rule[0].source[0].context = "src"
* group[0].rule[0].target[0].context = "tgt"
* group[0].rule[0].target[0].element = "extension"
* group[0].rule[0].target[0].variable = "t1"
* group[0].rule[0].target[1].context = "t1"
* group[0].rule[0].target[1].element = "url"
* group[0].rule[0].target[1].transform = #copy
* group[0].rule[0].target[1].parameter[0].valueString = "http://ihris.org/fhir/StructureDefinition/ihris-deployment"
* group[0].rule[0].rule[0].name = "deploymentDate"
* group[0].rule[0].rule[0].source[0].context = "src"
* group[0].rule[0].rule[0].source[0].element = "deploymentDate"
* group[0].rule[0].rule[0].source[0].variable = "s2"
* group[0].rule[0].rule[0].target[0].context = "t1"
* group[0].rule[0].rule[0].target[0].element = "extension"
* group[0].rule[0].rule[0].target[0].variable = "t3"
* group[0].rule[0].rule[0].target[1].context = "t3"
* group[0].rule[0].rule[0].target[1].element = "url"
* group[0].rule[0].rule[0].target[1].transform = #copy
* group[0].rule[0].rule[0].target[1].parameter[0].valueString = "date"
* group[0].rule[0].rule[0].target[2].context = "t3"
* group[0].rule[0].rule[0].target[2].element = "value"
* group[0].rule[0].rule[0].target[2].transform = #copy
* group[0].rule[0].rule[0].target[2].parameter[0].valueId = "s2"
