// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-verify-change-example-qualifysampledata-verify-change
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-verify-change-example-qualifysampledata-verify-change"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/verify_change-example-qualifysampledata-verify-change"
* version = "4.3.3"
* name = "IHRISVerifyChangeExampleQualifysampledataVerifyChange"
* title = "iHRIS Verification Change: sample data from ihris-qualify/module/QualifySampleData-verify_change"
* status = #draft
* experimental = true
* description = "SAMPLE records for `verify_change` from the iHRIS 4.3.3 module `ihris-qualify/module/QualifySampleData-verify_change`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 4
* concept[0].code = #1
* concept[0].display = "Record is Correct"
* concept[1].code = #2
* concept[1].display = "Update Demographics"
* concept[2].code = #3
* concept[2].display = "Updated Name/Address"
* concept[3].code = #4
* concept[3].display = "Corrected Incorrect Data"
