// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-disciplinary-action-type-example-sampledata-disciplinary-a
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-disciplinary-action-type-example-sampledata-disciplinary-a"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/disciplinary_action_type-example-sampledata-disciplinary-action-type"
* version = "4.3.3"
* name = "IHRISDisciplinaryActionTypeExampleSampledataDisciplinaryActionType"
* title = "iHRIS Disciplinary Action Type: sample data from ihris-manage/module/SampleData-disciplinary_action_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `disciplinary_action_type` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-disciplinary_action_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 5
* concept[0].code = #1
* concept[0].display = "Probation"
* concept[1].code = #2
* concept[1].display = "Warning"
* concept[2].code = #3
* concept[2].display = "None"
* concept[3].code = #4
* concept[3].display = "Invalid"
* concept[4].code = #5
* concept[4].display = "Dismissal"
