// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-gender
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-gender"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/gender"
* version = "4.3.3"
* name = "IHRISGender"
* title = "iHRIS Gender"
* status = #draft
* experimental = true
* description = "The `gender` list as shipped by default in iHRIS 4.3.3 (modules: ihris-common/module/PersonDemographic). Codes are the iHRIS record ids. Deployments add their own records, so this is the shipped baseline, not a closed international code set."
* caseSensitive = true
* content = #complete
* count = 2
* concept[0].code = #F
* concept[0].display = "Female"
* concept[1].code = #M
* concept[1].display = "Male"
