// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-county-example-sampledata-county
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-county-example-sampledata-county"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/county-example-sampledata-county"
* version = "4.3.3"
* name = "IHRISCountyExampleSampledataCounty"
* title = "iHRIS County: sample data from ihris-common/module/SampleData-county"
* status = #draft
* experimental = true
* description = "SAMPLE records for `county` from the iHRIS 4.3.3 module `ihris-common/module/SampleData-county`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 3
* property[0].code = #district
* property[0].type = #Coding
* property[0].description = "iHRIS MAP field `district`: a code in the district list"
* concept[0].code = #1
* concept[0].display = "Hiyala"
* concept[0].property[0].code = #district
* concept[0].property[0].valueCoding.system = "https://litlfred.github.io/ihris/dak/CodeSystem/district-example-sampledata-district"
* concept[0].property[0].valueCoding.code = #41
* concept[1].code = #2
* concept[1].display = "Orange"
* concept[1].property[0].code = #district
* concept[1].property[0].valueCoding.system = "https://litlfred.github.io/ihris/dak/CodeSystem/district-example-sampledata-district"
* concept[1].property[0].valueCoding.code = #40
* concept[2].code = #3
* concept[2].display = "Durham"
* concept[2].property[0].code = #district
* concept[2].property[0].valueCoding.system = "https://litlfred.github.io/ihris/dak/CodeSystem/district-example-sampledata-district"
* concept[2].property[0].valueCoding.code = #40
