// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-exam-try
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-exam-try"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/exam_try"
* version = "4.3.3"
* name = "IHRISExamTry"
* title = "iHRIS Exam Try"
* status = #draft
* experimental = true
* description = "The `exam_try` list as shipped by default in iHRIS 4.3.3 (modules: ihris-qualify/module/ihris-qualify). Codes are the iHRIS record ids. Deployments add their own records, so this is the shipped baseline, not a closed international code set."
* caseSensitive = true
* content = #complete
* count = 3
* concept[0].code = #first
* concept[0].display = "First Try"
* concept[1].code = #retry
* concept[1].display = "Re-Try"
* concept[2].code = #final
* concept[2].display = "Final Try"
