// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-salary-source-example-sampledata-salary-source
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-salary-source-example-sampledata-salary-source"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/salary_source-example-sampledata-salary-source"
* version = "4.3.3"
* name = "IHRISSalarySourceExampleSampledataSalarySource"
* title = "iHRIS Salary Source: sample data from ihris-manage/module/SampleData-salary_source"
* status = #draft
* experimental = true
* description = "SAMPLE records for `salary_source` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-salary_source`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 7
* concept[0].code = #1
* concept[0].display = "Private Non-profit (NGO)"
* concept[1].code = #2
* concept[1].display = "Private For-profit (Commercial)"
* concept[2].code = #3
* concept[2].display = "Individual Donor"
* concept[3].code = #4
* concept[3].display = "Faith-based Organization (FBO)"
* concept[4].code = #5
* concept[4].display = "Association"
* concept[5].code = #6
* concept[5].display = "Ministry of Health"
* concept[6].code = #7
* concept[6].display = "Private"
