// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-training-course-requestor-example-sampledata-training-cour
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-training-course-requestor-example-sampledata-training-cour"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/training_course_requestor-example-sampledata-training-course-requestor"
* version = "4.3.3"
* name = "IHRISTrainingCourseRequestorExampleSampledataTrainingCourseRequestor"
* title = "iHRIS Training Requestor: sample data from ihris-manage/module/SampleData-training_course_requestor"
* status = #draft
* experimental = true
* description = "SAMPLE records for `training_course_requestor` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-training_course_requestor`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 5
* concept[0].code = #1
* concept[0].display = "Employee"
* concept[1].code = #2
* concept[1].display = "Supervisor"
* concept[2].code = #3
* concept[2].display = "Human Resources"
* concept[3].code = #4
* concept[3].display = "Donor"
* concept[4].code = #5
* concept[4].display = "Other"
