// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-training-course-exam-type
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-training-course-exam-type"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/training_course_exam_type"
* version = "4.3.3"
* name = "IHRISTrainingCourseExamType"
* title = "iHRIS Training Course Exam Type"
* status = #draft
* experimental = true
* description = "The `training_course_exam_type` list as shipped by default in iHRIS 4.3.3 (modules: ihris-common/module/training-exam). Codes are the iHRIS record ids. Deployments add their own records, so this is the shipped baseline, not a closed international code set."
* caseSensitive = true
* content = #complete
* count = 3
* concept[0].code = #final
* concept[0].display = "Final"
* concept[1].code = #incourse
* concept[1].display = "In Course Exam"
* concept[2].code = #pretest
* concept[2].display = "PreTest"
