// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-benefit-type-example-sampledata-benefit-type
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-benefit-type-example-sampledata-benefit-type"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/benefit_type-example-sampledata-benefit-type"
* version = "4.3.3"
* name = "IHRISBenefitTypeExampleSampledataBenefitType"
* title = "iHRIS Benefit Type: sample data from ihris-manage/module/SampleData-benefit_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `benefit_type` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-benefit_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 4
* concept[0].code = #1
* concept[0].display = "Allowance"
* concept[1].code = #2
* concept[1].display = "Bonus"
* concept[2].code = #3
* concept[2].display = "Travel Advance"
* concept[3].code = #4
* concept[3].display = "Expense"
