// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-edu-type-example-sampledata-edu-type
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-edu-type-example-sampledata-edu-type"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/edu_type-example-sampledata-edu-type"
* version = "4.3.3"
* name = "IHRISEduTypeExampleSampledataEduType"
* title = "iHRIS Education Type: sample data from ihris-common/module/SampleData-edu_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `edu_type` from the iHRIS 4.3.3 module `ihris-common/module/SampleData-edu_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 5
* concept[0].code = #1
* concept[0].display = "Degree/Certification"
* concept[1].code = #2
* concept[1].display = "Continuing Education"
* concept[2].code = #3
* concept[2].display = "Informal"
* concept[3].code = #4
* concept[3].display = "Other"
* concept[4].code = #5
* concept[4].display = "High School"
