// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-language-example-sampledata-language
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-language-example-sampledata-language"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/language-example-sampledata-language"
* version = "4.3.3"
* name = "IHRISLanguageExampleSampledataLanguage"
* title = "iHRIS Language: sample data from ihris-manage/module/SampleData-language"
* status = #draft
* experimental = true
* description = "SAMPLE records for `language` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-language`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 9
* concept[0].code = #1
* concept[0].display = "Taifafeki"
* concept[1].code = #2
* concept[1].display = "French"
* concept[2].code = #3
* concept[2].display = "English"
* concept[3].code = #4
* concept[3].display = "Spanish"
* concept[4].code = #5
* concept[4].display = "Kinyarwanda"
* concept[5].code = #6
* concept[5].display = "Swahili"
* concept[6].code = #7
* concept[6].display = "Italian"
* concept[7].code = #8
* concept[7].display = "Dutch"
* concept[8].code = #9
* concept[8].display = "German"
