// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-pos-change-reason-example-sampledata-pos-change-reason
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-pos-change-reason-example-sampledata-pos-change-reason"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/pos_change_reason-example-sampledata-pos-change-reason"
* version = "4.3.3"
* name = "IHRISPosChangeReasonExampleSampledataPosChangeReason"
* title = "iHRIS Reasons for Departure: sample data from ihris-manage/module/SampleData-pos_change_reason"
* status = #draft
* experimental = true
* description = "SAMPLE records for `pos_change_reason` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-pos_change_reason`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 9
* concept[0].code = #1
* concept[0].display = "Illness/Disability"
* concept[1].code = #2
* concept[1].display = "Relocation"
* concept[2].code = #3
* concept[2].display = "Out Migration"
* concept[3].code = #4
* concept[3].display = "Death"
* concept[4].code = #5
* concept[4].display = "New Position"
* concept[5].code = #6
* concept[5].display = "Internal Promotion"
* concept[6].code = #7
* concept[6].display = "Involuntary Separation"
* concept[7].code = #8
* concept[7].display = "Retirement"
* concept[8].code = #9
* concept[8].display = "Voluntary Separation"
