// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-competency-type-example-sampledata-competency-type
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-competency-type-example-sampledata-competency-type"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/competency_type-example-sampledata-competency-type"
* version = "4.3.3"
* name = "IHRISCompetencyTypeExampleSampledataCompetencyType"
* title = "iHRIS Competency Type: sample data from ihris-manage/module/SampleData-competency_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `competency_type` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-competency_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 15
* concept[0].code = #1
* concept[0].display = "Pharmacy"
* concept[1].code = #2
* concept[1].display = "Public Health"
* concept[2].code = #3
* concept[2].display = "Secretarial"
* concept[3].code = #4
* concept[3].display = "Nursing/Midwifery"
* concept[4].code = #5
* concept[4].display = "Medicine"
* concept[5].code = #6
* concept[5].display = "Information Technology"
* concept[6].code = #7
* concept[6].display = "Accounting"
* concept[7].code = #8
* concept[7].display = "Administration"
* concept[8].code = #9
* concept[8].display = "Protective Services"
* concept[9].code = #10
* concept[9].display = "Physiotherapy"
* concept[10].code = #11
* concept[10].display = "Housekeeping"
* concept[11].code = #12
* concept[11].display = "Management"
* concept[12].code = #13
* concept[12].display = "Optometry"
* concept[13].code = #14
* concept[13].display = "Dentistry"
* concept[14].code = #15
* concept[14].display = "Logistics"
