// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-accident-type-example-sampledata-accident-type
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-accident-type-example-sampledata-accident-type"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/accident_type-example-sampledata-accident-type"
* version = "4.3.3"
* name = "IHRISAccidentTypeExampleSampledataAccidentType"
* title = "iHRIS Workplace Accident Type: sample data from ihris-manage/module/SampleData-accident_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `accident_type` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-accident_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 5
* concept[0].code = #1
* concept[0].display = "Minor Injury"
* concept[1].code = #2
* concept[1].display = "Major Injury"
* concept[2].code = #3
* concept[2].display = "Death"
* concept[3].code = #4
* concept[3].display = "Minor Damage to Property"
* concept[4].code = #5
* concept[4].display = "Major Damage to Property"
