// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-marital-status-example-sampledata-marital-status
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-marital-status-example-sampledata-marital-status"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/marital_status-example-sampledata-marital-status"
* version = "4.3.3"
* name = "IHRISMaritalStatusExampleSampledataMaritalStatus"
* title = "iHRIS Marital Status: sample data from ihris-common/module/SampleData-marital_status"
* status = #draft
* experimental = true
* description = "SAMPLE records for `marital_status` from the iHRIS 4.3.3 module `ihris-common/module/SampleData-marital_status`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 5
* concept[0].code = #1
* concept[0].display = "Single"
* concept[1].code = #2
* concept[1].display = "Married"
* concept[2].code = #3
* concept[2].display = "Widowed"
* concept[3].code = #4
* concept[3].display = "Divorced"
* concept[4].code = #5
* concept[4].display = "Domestic Partner"
