// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-classification-example-sampledata-classification
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-classification-example-sampledata-classification"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/classification-example-sampledata-classification"
* version = "4.3.3"
* name = "IHRISClassificationExampleSampledataClassification"
* title = "iHRIS Classification: sample data from ihris-manage/module/SampleData-classification"
* status = #draft
* experimental = true
* description = "SAMPLE records for `classification` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-classification`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 6
* property[0].code = #description
* property[0].type = #string
* property[0].description = "iHRIS field `description`"
* property[1].code = #code
* property[1].type = #string
* property[1].description = "iHRIS field `code`"
* concept[0].code = #1
* concept[0].display = "Medical Doctor"
* concept[0].property[0].code = #description
* concept[0].property[0].valueString = "Medical doctors"
* concept[0].property[1].code = #code
* concept[0].property[1].valueString = "222"
* concept[1].code = #2
* concept[1].display = "Nurse"
* concept[1].property[0].code = #description
* concept[1].property[0].valueString = "Nursing and midwifery professionals"
* concept[1].property[1].code = #code
* concept[1].property[1].valueString = "223"
* concept[2].code = #3
* concept[2].display = "Allied Health Professional"
* concept[2].property[0].code = #description
* concept[2].property[0].valueString = "Modern health associate professionals (except nursing)"
* concept[2].property[1].code = #code
* concept[2].property[1].valueString = "322"
* concept[3].code = #4
* concept[3].display = "Non-Health Professional"
* concept[3].property[0].code = #description
* concept[3].property[0].valueString = "Professionals, not health"
* concept[3].property[1].code = #code
* concept[3].property[1].valueString = "241"
* concept[4].code = #5
* concept[4].display = "Non-Health Support Staff"
* concept[4].property[0].code = #description
* concept[4].property[0].valueString = "Support staff, not health-related"
* concept[4].property[1].code = #code
* concept[4].property[1].valueString = "411"
* concept[5].code = #6
* concept[5].display = "Pharmacist"
* concept[5].property[0].code = #description
* concept[5].property[0].valueString = "Dispenses drugs."
