// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-council-example-sampledata-council
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-council-example-sampledata-council"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/council-example-sampledata-council"
* version = "4.3.3"
* name = "IHRISCouncilExampleSampledataCouncil"
* title = "iHRIS Council: sample data from ihris-manage/module/SampleData-council"
* status = #draft
* experimental = true
* description = "SAMPLE records for `council` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-council`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 5
* concept[0].code = #1
* concept[0].display = "Nurses and Midwives Council"
* concept[1].code = #2
* concept[1].display = "Pharmacy Council"
* concept[2].code = #3
* concept[2].display = "Allied Health Council"
* concept[3].code = #4
* concept[3].display = "Medical and Dental Council"
* concept[4].code = #5
* concept[4].display = "Other"
