// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-disciplinary-action-reason-example-sampledata-disciplinary
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-disciplinary-action-reason-example-sampledata-disciplinary"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/disciplinary_action_reason-example-sampledata-disciplinary-action-type"
* version = "4.3.3"
* name = "IHRISDisciplinaryActionReasonExampleSampledataDisciplinaryActionType"
* title = "iHRIS Disciplinary Action Reason: sample data from ihris-manage/module/SampleData-disciplinary_action_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `disciplinary_action_reason` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-disciplinary_action_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 15
* concept[0].code = #1
* concept[0].display = "Assessed Mentally Incompetent"
* concept[1].code = #2
* concept[1].display = "Death of Patient"
* concept[2].code = #3
* concept[2].display = "Drug-Related"
* concept[3].code = #4
* concept[3].display = "Failure to Disclose Criminal Conviction"
* concept[4].code = #5
* concept[4].display = "Falsification of Credentials"
* concept[5].code = #6
* concept[5].display = "Harm to Public"
* concept[6].code = #7
* concept[6].display = "Injury to Patient"
* concept[7].code = #8
* concept[7].display = "Insurance Fraud"
* concept[8].code = #9
* concept[8].display = "Minor Injury of Patient"
* concept[9].code = #10
* concept[9].display = "Permanent Injury of Patient"
* concept[10].code = #11
* concept[10].display = "Physical Abuse"
* concept[11].code = #12
* concept[11].display = "Serious Injury of Patient"
* concept[12].code = #13
* concept[12].display = "Stealing"
* concept[13].code = #14
* concept[13].display = "Verbal Abuse"
* concept[14].code = #15
* concept[14].display = "Practicing With Expired License"
