// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-confirmation-type-example-sampledata-confirmation-type
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-confirmation-type-example-sampledata-confirmation-type"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/confirmation_type-example-sampledata-confirmation-type"
* version = "4.3.3"
* name = "IHRISConfirmationTypeExampleSampledataConfirmationType"
* title = "iHRIS Confirmation Type: sample data from ihris-manage/module/SampleData-confirmation_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `confirmation_type` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-confirmation_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 2
* property[0].code = #i2ce_hidden
* property[0].type = #string
* property[0].description = "iHRIS field `i2ce_hidden`"
* property[1].code = #job
* property[1].type = #Coding
* property[1].description = "iHRIS MAP field `job`: a code in the job list"
* property[2].code = #probation_period
* property[2].type = #string
* property[2].description = "iHRIS field `probation_period`"
* concept[0].code = #1
* concept[0].display = "Six Month Confirmation"
* concept[0].property[0].code = #i2ce_hidden
* concept[0].property[0].valueString = "0"
* concept[0].property[1].code = #job
* concept[0].property[1].valueCoding.system = "https://litlfred.github.io/ihris/dak/CodeSystem/job-example-sampledata-job"
* concept[0].property[1].valueCoding.code = #2230-1B
* concept[0].property[2].code = #probation_period
* concept[0].property[2].valueString = "6"
* concept[1].code = #2
* concept[1].display = "Six Month Confirmation"
* concept[1].property[0].code = #i2ce_hidden
* concept[1].property[0].valueString = "0"
* concept[1].property[1].code = #job
* concept[1].property[1].valueCoding.system = "https://litlfred.github.io/ihris/dak/CodeSystem/job-example-sampledata-job"
* concept[1].property[1].valueCoding.code = #2230-2B
* concept[1].property[2].code = #probation_period
* concept[1].property[2].valueString = "6"
