// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-id-type-example-sampledata-id-type
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-id-type-example-sampledata-id-type"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/id_type-example-sampledata-id-type"
* version = "4.3.3"
* name = "IHRISIdTypeExampleSampledataIdType"
* title = "iHRIS Identification Type: sample data from ihris-manage/module/SampleData-id_type"
* status = #draft
* experimental = true
* description = "SAMPLE records for `id_type` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-id_type`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 4
* concept[0].code = #1
* concept[0].display = "Birth Certificate"
* concept[1].code = #2
* concept[1].display = "National Health Identification Number"
* concept[2].code = #3
* concept[2].display = "Passport Number"
* concept[3].code = #4
* concept[3].display = "Social Security Number"
