// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-language-proficiency
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-language-proficiency"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/language_proficiency"
* version = "4.3.3"
* name = "IHRISLanguageProficiency"
* title = "iHRIS Language Proficiency"
* status = #draft
* experimental = true
* description = "The `language_proficiency` list as shipped by default in iHRIS 4.3.3 (modules: ihris-common/module/PersonLanguage). Codes are the iHRIS record ids. Deployments add their own records, so this is the shipped baseline, not a closed international code set."
* caseSensitive = true
* content = #complete
* count = 5
* concept[0].code = #elementary
* concept[0].display = "Elementary"
* concept[1].code = #limited
* concept[1].display = "Limited Working"
* concept[2].code = #professional
* concept[2].display = "Professional Working"
* concept[3].code = #full_professional
* concept[3].display = "Full Professional"
* concept[4].code = #fluent
* concept[4].display = "Fluent"
