// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-leave-status
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-leave-status"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/leave_status"
* version = "4.3.3"
* name = "IHRISLeaveStatus"
* title = "iHRIS Leave Status"
* status = #draft
* experimental = true
* description = "The `leave_status` list as shipped by default in iHRIS 4.3.3 (modules: ihris-manage/module/leave_data). Codes are the iHRIS record ids. Deployments add their own records, so this is the shipped baseline, not a closed international code set."
* caseSensitive = true
* content = #complete
* count = 3
* property[0].code = #i2ce_hidden
* property[0].type = #string
* property[0].description = "iHRIS field `i2ce_hidden`"
* concept[0].code = #1
* concept[0].display = "Approved"
* concept[0].property[0].code = #i2ce_hidden
* concept[0].property[0].valueString = "0"
* concept[1].code = #2
* concept[1].display = "Denied"
* concept[1].property[0].code = #i2ce_hidden
* concept[1].property[0].valueString = "0"
* concept[2].code = #3
* concept[2].display = "Waiting Approval"
* concept[2].property[0].code = #i2ce_hidden
* concept[2].property[0].valueString = "0"
