// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-cadre-example-sampledata-cadre
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-cadre-example-sampledata-cadre"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/cadre-example-sampledata-cadre"
* version = "4.3.3"
* name = "IHRISCadreExampleSampledataCadre"
* title = "iHRIS Cadre: sample data from ihris-manage/module/SampleData-cadre"
* status = #draft
* experimental = true
* description = "SAMPLE records for `cadre` from the iHRIS 4.3.3 module `ihris-manage/module/SampleData-cadre`. Illustrative data for one fictional or example deployment. NOT a standard code set, and no ValueSet includes it."
* caseSensitive = true
* content = #example
* count = 4
* concept[0].code = #1
* concept[0].display = "Medical Doctor"
* concept[1].code = #2
* concept[1].display = "Nurse"
* concept[2].code = #3
* concept[2].display = "Allied Health Professional"
* concept[3].code = #4
* concept[3].display = "Pharmacist"
