// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: CodeSystem-ihris-benefit-recurrence
InstanceOf: CodeSystem
Usage: #definition
* id = "ihris-benefit-recurrence"
* url = "https://litlfred.github.io/ihris/dak/CodeSystem/benefit_recurrence"
* version = "4.3.3"
* name = "IHRISBenefitRecurrence"
* title = "iHRIS Benefit Recurrence"
* status = #draft
* experimental = true
* description = "The `benefit_recurrence` list as shipped by default in iHRIS 4.3.3 (modules: ihris-manage/module/ihris-manage-Benefit). Codes are the iHRIS record ids. Deployments add their own records, so this is the shipped baseline, not a closed international code set."
* caseSensitive = true
* content = #complete
* count = 4
* concept[0].code = #once
* concept[0].display = "Once"
* concept[1].code = #weekly
* concept[1].display = "Weekly"
* concept[2].code = #monthly
* concept[2].display = "Monthly"
* concept[3].code = #yearly
* concept[3].display = "Yearly"
