// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ConceptMap-classification-to-isco-88-minor
InstanceOf: ConceptMap
Usage: #definition
* id = "classification-to-isco-88-minor"
* url = "https://litlfred.github.io/ihris/dak/ConceptMap/classification-to-isco-88-minor"
* version = "4.3.3"
* name = "ClassificationToIsco88Minor"
* title = "iHRIS sample classifications to ISCO-88 minor groups"
* status = #draft
* experimental = true
* description = "Derived from the iHRIS SAMPLE classification list, whose `code` field holds an ISCO-88 minor group."
* sourceUri = "https://litlfred.github.io/ihris/dak/ValueSet/classification"
* targetUri = "https://litlfred.github.io/ihris/dak/ValueSet/isco_88_minor"
* group[0].source = "https://litlfred.github.io/ihris/dak/CodeSystem/classification-example-sampledata-classification"
* group[0].target = "https://litlfred.github.io/ihris/dak/CodeSystem/isco_88_minor"
* group[0].element[0].code = #1
* group[0].element[0].display = "Medical Doctor"
* group[0].element[0].target[0].code = #222
* group[0].element[0].target[0].display = "HEALTH PROFESSIONALS (except nursing)"
* group[0].element[0].target[0].equivalence = #equivalent
* group[0].element[0].target[0].comment = "Asserted by the record's own `code` field; verified against iHRIS's shipped ISCO-88 minor groups."
* group[0].element[1].code = #2
* group[0].element[1].display = "Nurse"
* group[0].element[1].target[0].code = #223
* group[0].element[1].target[0].display = "NURSING AND MIDWIFERY PROFESSIONALS"
* group[0].element[1].target[0].equivalence = #equivalent
* group[0].element[1].target[0].comment = "Asserted by the record's own `code` field; verified against iHRIS's shipped ISCO-88 minor groups."
* group[0].element[2].code = #3
* group[0].element[2].display = "Allied Health Professional"
* group[0].element[2].target[0].code = #322
* group[0].element[2].target[0].display = "MODERN HEALTH ASSOCIATE PROFESSIONALS (except nursing)"
* group[0].element[2].target[0].equivalence = #equivalent
* group[0].element[2].target[0].comment = "Asserted by the record's own `code` field; verified against iHRIS's shipped ISCO-88 minor groups."
* group[0].element[3].code = #4
* group[0].element[3].display = "Non-Health Professional"
* group[0].element[3].target[0].code = #241
* group[0].element[3].target[0].display = "BUSINESS PROFESSIONALS"
* group[0].element[3].target[0].equivalence = #equivalent
* group[0].element[3].target[0].comment = "Asserted by the record's own `code` field; verified against iHRIS's shipped ISCO-88 minor groups."
* group[0].element[4].code = #5
* group[0].element[4].display = "Non-Health Support Staff"
* group[0].element[4].target[0].code = #411
* group[0].element[4].target[0].display = "SECRETARIES AND KEYBOARD-OPERATING CLERKS"
* group[0].element[4].target[0].equivalence = #equivalent
* group[0].element[4].target[0].comment = "Asserted by the record's own `code` field; verified against iHRIS's shipped ISCO-88 minor groups."
* group[0].element[5].code = #6
* group[0].element[5].display = "Pharmacist"
* group[0].element[5].target[0].equivalence = #unmatched
* group[0].element[5].target[0].comment = "The record carries no ISCO-88 code."
