// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-out-migration-reason
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-out-migration-reason"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/out_migration_reason"
* version = "4.3.3"
* name = "IHRISOutMigrationReasonVS"
* title = "iHRIS Out Migration Reason"
* status = #draft
* experimental = true
* description = "The iHRIS `out_migration_reason` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
