// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-salary-source
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-salary-source"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/salary_source"
* version = "4.3.3"
* name = "IHRISSalarySourceVS"
* title = "iHRIS Salary Source"
* status = #draft
* experimental = true
* description = "The iHRIS `salary_source` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-salary_source)."
