// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-language-proficiency
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-language-proficiency"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/language_proficiency"
* version = "4.3.3"
* name = "IHRISLanguageProficiencyVS"
* title = "iHRIS Language Proficiency"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `language_proficiency` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/language_proficiency"
