// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-verify-change
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-verify-change"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/verify_change"
* version = "4.3.3"
* name = "IHRISVerifyChangeVS"
* title = "iHRIS Verification Change"
* status = #draft
* experimental = true
* description = "The iHRIS `verify_change` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-qualify/module/QualifySampleData-verify_change)."
