// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-marital-status
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-marital-status"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/marital_status"
* version = "4.3.3"
* name = "IHRISMaritalStatusVS"
* title = "iHRIS Marital Status"
* status = #draft
* experimental = true
* description = "The iHRIS `marital_status` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-common/module/SampleData-marital_status, ihris-qualify/module/QualifySampleData-marital_status)."
