// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-gender
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-gender"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/gender"
* version = "4.3.3"
* name = "IHRISGenderVS"
* title = "iHRIS Gender"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `gender` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/gender"
