// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-training-program
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-training-program"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/training_program"
* version = "4.3.3"
* name = "IHRISTrainingProgramVS"
* title = "iHRIS Training Program"
* status = #draft
* experimental = true
* description = "The iHRIS `training_program` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
