// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-salary-grade
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-salary-grade"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/salary_grade"
* version = "4.3.3"
* name = "IHRISSalaryGradeVS"
* title = "iHRIS Salary Grade"
* status = #draft
* experimental = true
* description = "The iHRIS `salary_grade` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-salary_grade)."
