// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-isco-88-minor
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-isco-88-minor"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/isco_88_minor"
* version = "4.3.3"
* name = "IHRISIsco88MinorVS"
* title = "iHRIS ISCO 88 Minor"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `isco_88_minor` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/isco_88_minor"
