// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-region
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-region"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/region"
* version = "4.3.3"
* name = "IHRISRegionVS"
* title = "iHRIS Region"
* status = #draft
* experimental = true
* description = "The iHRIS `region` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-common/module/SampleData-region)."
