// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-competency-type
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-competency-type"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/competency_type"
* version = "4.3.3"
* name = "IHRISCompetencyTypeVS"
* title = "iHRIS Competency Type"
* status = #draft
* experimental = true
* description = "The iHRIS `competency_type` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-competency_type)."
