// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-isco-88-sub-major
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-isco-88-sub-major"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/isco_88_sub_major"
* version = "4.3.3"
* name = "IHRISIsco88SubMajorVS"
* title = "iHRIS ISCO 88 Sub-Major"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `isco_88_sub_major` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/isco_88_sub_major"
