// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-continuing-education-course
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-continuing-education-course"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/continuing_education_course"
* version = "4.3.3"
* name = "IHRISContinuingEducationCourseVS"
* title = "iHRIS Continuing Education Course"
* status = #draft
* experimental = true
* description = "The iHRIS `continuing_education_course` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
