// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-benefit-recurrence
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-benefit-recurrence"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/benefit_recurrence"
* version = "4.3.3"
* name = "IHRISBenefitRecurrenceVS"
* title = "iHRIS Benefit Recurrence"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `benefit_recurrence` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/benefit_recurrence"
