// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-training-course-requestor
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-training-course-requestor"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/training_course_requestor"
* version = "4.3.3"
* name = "IHRISTrainingCourseRequestorVS"
* title = "iHRIS Training Requestor"
* status = #draft
* experimental = true
* description = "The iHRIS `training_course_requestor` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-training_course_requestor)."
