// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-training-course-exam-type
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-training-course-exam-type"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/training_course_exam_type"
* version = "4.3.3"
* name = "IHRISTrainingCourseExamTypeVS"
* title = "iHRIS Training Course Exam Type"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `training_course_exam_type` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/training_course_exam_type"
