// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-job
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-job"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/job"
* version = "4.3.3"
* name = "IHRISJobVS"
* title = "iHRIS Job"
* status = #draft
* experimental = true
* description = "The iHRIS `job` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-job)."
