// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-accident-type
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-accident-type"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/accident_type"
* version = "4.3.3"
* name = "IHRISAccidentTypeVS"
* title = "iHRIS Workplace Accident Type"
* status = #draft
* experimental = true
* description = "The iHRIS `accident_type` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-accident_type)."
