// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-district
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-district"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/district"
* version = "4.3.3"
* name = "IHRISDistrictVS"
* title = "iHRIS District"
* status = #draft
* experimental = true
* description = "The iHRIS `district` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-common/module/SampleData-district)."
