// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-id-type
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-id-type"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/id_type"
* version = "4.3.3"
* name = "IHRISIdTypeVS"
* title = "iHRIS Identification Type"
* status = #draft
* experimental = true
* description = "The iHRIS `id_type` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-id_type, ihris-qualify/module/QualifySampleData-id_type)."
