// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-country
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-country"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/country"
* version = "4.3.3"
* name = "IHRISCountryVS"
* title = "iHRIS Country"
* status = #draft
* experimental = true
* description = "All current codes of ISO 3166-1 alpha-2 (urn:iso:std:iso:3166). The DAK binds to the standard, not to iHRIS's shipped `country` list; that list is CodeSystem `country` here, mapped to the standard by ConceptMap `country-to-iso-3166`."
* compose.include[0].system = "urn:iso:std:iso:3166"
