// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-confirmation-type
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-confirmation-type"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/confirmation_type"
* version = "4.3.3"
* name = "IHRISConfirmationTypeVS"
* title = "iHRIS Confirmation Type"
* status = #draft
* experimental = true
* description = "The iHRIS `confirmation_type` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-confirmation_type)."
