// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-exam-try
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-exam-try"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/exam_try"
* version = "4.3.3"
* name = "IHRISExamTryVS"
* title = "iHRIS Exam Try"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `exam_try` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/exam_try"
