// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-pos-change-reason
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-pos-change-reason"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/pos_change_reason"
* version = "4.3.3"
* name = "IHRISPosChangeReasonVS"
* title = "iHRIS Reasons for Departure"
* status = #draft
* experimental = true
* description = "The iHRIS `pos_change_reason` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-pos_change_reason)."
