// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-certificate
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-certificate"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/certificate"
* version = "4.3.3"
* name = "IHRISCertificateVS"
* title = "iHRIS Certificate"
* status = #draft
* experimental = true
* description = "The iHRIS `certificate` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
