// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-training-disruption-reason
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-training-disruption-reason"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/training_disruption_reason"
* version = "4.3.3"
* name = "IHRISTrainingDisruptionReasonVS"
* title = "iHRIS Training Disruption Reason"
* status = #draft
* experimental = true
* description = "The iHRIS `training_disruption_reason` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
