// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-leave-status
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-leave-status"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/leave_status"
* version = "4.3.3"
* name = "IHRISLeaveStatusVS"
* title = "iHRIS Leave Status"
* status = #draft
* experimental = true
* description = "All codes of the iHRIS `leave_status` list as shipped by default in iHRIS 4.3.3."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/leave_status"
