// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-benefit-type
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-benefit-type"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/benefit_type"
* version = "4.3.3"
* name = "IHRISBenefitTypeVS"
* title = "iHRIS Benefit Type"
* status = #draft
* experimental = true
* description = "The iHRIS `benefit_type` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-benefit_type)."
