// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-training-institution
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-training-institution"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/training_institution"
* version = "4.3.3"
* name = "IHRISTrainingInstitutionVS"
* title = "iHRIS Training Institution"
* status = #draft
* experimental = true
* description = "The iHRIS `training_institution` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
