// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-isco-08-major
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-isco-08-major"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/isco_08_major"
* version = "4.3.3"
* name = "IHRISISCO08MajorVS"
* title = "ISCO-08 major groups (as shipped in iHRIS)"
* status = #draft
* experimental = true
* description = "The 10 ISCO-08 major groups iHRIS 4.3.3 ships by default (`isco_08_major`), as codes of the ILO ISCO-08 system under the ILO's system URL (http://www.ilo.org/public/english/bureau/stat/isco/isco08/)."
* compose.include[0].system = "http://www.ilo.org/public/english/bureau/stat/isco/isco08/"
* compose.include[0].concept[0].code = #0
* compose.include[0].concept[0].display = "Armed forces occupations"
* compose.include[0].concept[1].code = #1
* compose.include[0].concept[1].display = "Managers"
* compose.include[0].concept[2].code = #2
* compose.include[0].concept[2].display = "Professionals"
* compose.include[0].concept[3].code = #3
* compose.include[0].concept[3].display = "Technicians and associate professionals"
* compose.include[0].concept[4].code = #4
* compose.include[0].concept[4].display = "Clerical support workers"
* compose.include[0].concept[5].code = #5
* compose.include[0].concept[5].display = "Service and sales workers"
* compose.include[0].concept[6].code = #6
* compose.include[0].concept[6].display = "Skilled agricultural, forestry and fishery workers"
* compose.include[0].concept[7].code = #7
* compose.include[0].concept[7].display = "Craft and related trades workers"
* compose.include[0].concept[8].code = #8
* compose.include[0].concept[8].display = "Plant and machine operators, and assemblers"
* compose.include[0].concept[9].code = #9
* compose.include[0].concept[9].display = "Elementary occupations"
