// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-disciplinary-action-reason
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-disciplinary-action-reason"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/disciplinary_action_reason"
* version = "4.3.3"
* name = "IHRISDisciplinaryActionReasonVS"
* title = "iHRIS Disciplinary Action Reason"
* status = #draft
* experimental = true
* description = "The iHRIS `disciplinary_action_reason` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-disciplinary_action_type)."
