// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-position
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-position"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/position"
* version = "4.3.3"
* name = "IHRISPositionVS"
* title = "iHRIS Position"
* status = #draft
* experimental = true
* description = "The iHRIS `position` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
