// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-classification
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-classification"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/classification"
* version = "4.3.3"
* name = "IHRISClassificationVS"
* title = "iHRIS Classification"
* status = #draft
* experimental = true
* description = "The iHRIS `classification` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-classification)."
