// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-cadre
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-cadre"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/cadre"
* version = "4.3.3"
* name = "IHRISCadreVS"
* title = "iHRIS Cadre"
* status = #draft
* experimental = true
* description = "The iHRIS `cadre` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-manage/module/SampleData-cadre)."
