// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-currency
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-currency"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/currency"
* version = "4.3.3"
* name = "IHRISCurrencyVS"
* title = "iHRIS Currency"
* status = #draft
* experimental = true
* description = "All current codes of ISO 4217 (urn:iso:std:iso:4217). The DAK binds to the standard, not to iHRIS's shipped `currency` list; that list is CodeSystem `currency` here, mapped to the standard by ConceptMap `currency-to-iso-4217`."
* compose.include[0].system = "urn:iso:std:iso:4217"
