// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-edu-type
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-edu-type"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/edu_type"
* version = "4.3.3"
* name = "IHRISEduTypeVS"
* title = "iHRIS Education Type"
* status = #draft
* experimental = true
* description = "The iHRIS `edu_type` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment (sample data exists: ihris-common/module/SampleData-edu_type)."
