// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-country-shipped
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-country-shipped"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/country-shipped"
* version = "4.3.3"
* name = "IHRISCountryShippedVS"
* title = "iHRIS country list as shipped"
* status = #draft
* experimental = true
* description = "Every code of the `country` list iHRIS 4.3.3 ships by default: the source side of ConceptMap `country-to-iso-3166`."
* compose.include[0].system = "https://litlfred.github.io/ihris/dak/CodeSystem/country"
