// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-training-course-mod
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-training-course-mod"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/training_course_mod"
* version = "4.3.3"
* name = "IHRISTrainingCourseModVS"
* title = "iHRIS Training Course Module"
* status = #draft
* experimental = true
* description = "The iHRIS `training_course_mod` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
