// GENERATED by src/tools/gen_fsh.py from src/tools/build_dak.py. Do not edit: change the source or the generator.

Instance: ValueSet-ihris-scheduled-training-course
InstanceOf: ValueSet
Usage: #definition
* id = "ihris-scheduled-training-course"
* url = "https://litlfred.github.io/ihris/dak/ValueSet/scheduled_training_course"
* version = "4.3.3"
* name = "IHRISScheduledTrainingCourseVS"
* title = "iHRIS Scheduled Training Course"
* status = #draft
* experimental = true
* description = "The iHRIS `scheduled_training_course` list. iHRIS 4.3.3 ships no default records for it: its codes are defined by each deployment."
