// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Accident.json. Do not edit: change the source or the generator.

Logical: Accident
Id: Accident
Title: "Accident"
Description: "The iHRIS 4.3.3 form class `iHRIS_Accident` (forms: accident; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_Accident."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Accident"
* ^version = "4.3.3"
* ^status = #draft
* occurenceDate 0..1 date "Date of Occurence"
* accidentType 1..1 Coding "Accident Type"
* accidentType from https://litlfred.github.io/ihris/dak/ValueSet/accident_type (extensible)
* startDate 1..1 date "Start of Applicability"
* endDate 0..1 date "End of Applicability"
* followup 0..1 string "Follow-up Required"
* personsInvolved 0..1 string "People Involved"

Mapping: Accident-I2CE
Id: i2ce
Source: Accident
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Accident"
* -> "iHRIS_Accident"
* occurenceDate -> "occurence_date"
* accidentType -> "accident_type"
* startDate -> "start_date"
* endDate -> "end_date"
* followup -> "followup"
* personsInvolved -> "persons_involved"
