// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Applicant.json. Do not edit: change the source or the generator.

Logical: Applicant
Id: Applicant
Title: "Applicant"
Description: "The iHRIS 4.3.3 form class `iHRIS_Applicant` (forms: application; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_Applicant."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Applicant"
* ^version = "4.3.3"
* ^status = #draft
* position 1..* Coding "Position(s)"
* position from https://litlfred.github.io/ihris/dak/ValueSet/position (extensible)
* felony 0..1 boolean "Have you ever been convicted of a felony?"
* felonyCircumstance 0..1 string "If yes, give the circumstances."
* otherInfo 0..1 string "In addition to your work history, are there other skills, qualifications or experience we should consider?"
* hear 0..1 string "How did you hear of this opening?"
* startDate 0..1 date "When can you start?"
* desiredWage 0..1 Money "Desired Wage"
* fullTime 0..1 boolean "Are you looking for full-time employment?"
* hours 0..1 string "If no, what hours are you available?"

Mapping: Applicant-I2CE
Id: i2ce
Source: Applicant
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Applicant"
* -> "iHRIS_Applicant"
* position -> "position"
* felony -> "felony"
* felonyCircumstance -> "felony_circumstance"
* otherInfo -> "other_info"
* hear -> "hear"
* startDate -> "start_date"
* desiredWage -> "desired_wage"
* fullTime -> "full_time"
* hours -> "hours"
