// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Benefit.json. Do not edit: change the source or the generator.

Logical: Benefit
Id: Benefit
Title: "Benefit"
Description: "The iHRIS 4.3.3 form class `iHRIS_Benefit` (forms: benefit; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_Benefit."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Benefit"
* ^version = "4.3.3"
* ^status = #draft
* type 1..1 Coding "Benefit Type"
* type from https://litlfred.github.io/ihris/dak/ValueSet/benefit_type (extensible)
* amount 1..1 Money "Amount"
* source 1..1 Coding "Source"
* source from https://litlfred.github.io/ihris/dak/ValueSet/salary_source (extensible)
* startDate 1..1 date "Start Date"
* endDate 0..1 date "End Date"
* recurrence 1..1 Coding "Recurrence Frequency"
* recurrence from https://litlfred.github.io/ihris/dak/ValueSet/benefit_recurrence (extensible)

Mapping: Benefit-I2CE
Id: i2ce
Source: Benefit
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Benefit"
* -> "iHRIS_Benefit"
* type -> "type"
* amount -> "amount"
* source -> "source"
* startDate -> "start_date"
* endDate -> "end_date"
* recurrence -> "recurrence"
