// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Confirmation.json. Do not edit: change the source or the generator.

Logical: Confirmation
Id: Confirmation
Title: "Confirmation"
Description: "The iHRIS 4.3.3 form class `iHRIS_Confirmation` (forms: confirmation; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_Confirmation."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Confirmation"
* ^version = "4.3.3"
* ^status = #draft
* valid 1..1 boolean "Valid"
* confirmationType 1..1 Coding "Confirmation Type"
* confirmationType from https://litlfred.github.io/ihris/dak/ValueSet/confirmation_type (extensible)
* date 1..1 date "Date"
* record 0..1 Attachment "Record"

Mapping: Confirmation-I2CE
Id: i2ce
Source: Confirmation
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Confirmation"
* -> "iHRIS_Confirmation"
* valid -> "valid"
* confirmationType -> "confirmation_type"
* date -> "date"
* record -> "record"
