// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Contact.json. Do not edit: change the source or the generator.

Logical: Contact
Id: Contact
Title: "Contact"
Description: "The iHRIS 4.3.3 form class `iHRIS_Contact` (forms: contact, facility_contact, person_contact_other, person_contact_personal, person_contact_work, training_funder_contact, training_institution_contact; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Contact."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Contact"
* ^version = "4.3.3"
* ^status = #draft
* address 0..* string "Mailing Address"
* telephone 0..* string "Telephone Number"
* mobilePhone 0..* string "Mobile Phone Number"
* altTelephone 0..* string "Alternate Telephone Number"
* fax 0..* string "Fax Number"
* email 0..* string "Email Address"
* notes 0..* string "Notes"

Mapping: Contact-I2CE
Id: i2ce
Source: Contact
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Contact"
* -> "iHRIS_Contact"
* address -> "address"
* telephone -> "telephone"
* mobilePhone -> "mobile_phone"
* altTelephone -> "alt_telephone"
* fax -> "fax"
* email -> "email"
* notes -> "notes"
