// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/ContinuingEducation.json. Do not edit: change the source or the generator.

Logical: ContinuingEducation
Id: ContinuingEducation
Title: "Continuing Education"
Description: "The iHRIS 4.3.3 form class `iHRIS_ContinuingEducation` (forms: continuing_education; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_ContinuingEducation."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/ContinuingEducation"
* ^version = "4.3.3"
* ^status = #draft
* continuingEducationCourse 1..1 Coding "Continuing Education Course"
* continuingEducationCourse from https://litlfred.github.io/ihris/dak/ValueSet/continuing_education_course (extensible)
* creditHours 1..1 integer "Credit Hours"
* startDate 1..1 date "Start Date"
* endDate 1..1 date "End Date"

Mapping: ContinuingEducation-I2CE
Id: i2ce
Source: ContinuingEducation
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_ContinuingEducation"
* -> "iHRIS_ContinuingEducation"
* continuingEducationCourse -> "continuing_education_course"
* creditHours -> "credit_hours"
* startDate -> "start_date"
* endDate -> "end_date"
