// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Demographic.json. Do not edit: change the source or the generator.

Logical: Demographic
Id: Demographic
Title: "Demographic Information"
Description: "The iHRIS 4.3.3 form class `iHRIS_Demographic` (forms: demographic; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Demographic."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Demographic"
* ^version = "4.3.3"
* ^status = #draft
* birthDate 0..1 date "Date of Birth"
* gender 0..1 Coding "Gender"
* gender from https://litlfred.github.io/ihris/dak/ValueSet/gender (extensible)
* maritalStatus 0..1 Coding "Marital Status"
* maritalStatus from https://litlfred.github.io/ihris/dak/ValueSet/marital_status (extensible)

Mapping: Demographic-I2CE
Id: i2ce
Source: Demographic
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Demographic"
* -> "iHRIS_Demographic"
* birthDate -> "birth_date"
* gender -> "gender"
* maritalStatus -> "marital_status"
