// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Dependent.json. Do not edit: change the source or the generator.

Logical: Dependent
Id: Dependent
Title: "Dependent"
Description: "The iHRIS 4.3.3 form class `iHRIS_Dependent` (forms: dependent; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Dependent."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Dependent"
* ^version = "4.3.3"
* ^status = #draft
* gender 0..1 Coding "Gender"
* gender from https://litlfred.github.io/ihris/dak/ValueSet/gender (extensible)
* dateOfBirth 0..1 date "Date of Birth"
* name 1..1 string "Name"

Mapping: Dependent-I2CE
Id: i2ce
Source: Dependent
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Dependent"
* -> "iHRIS_Dependent"
* gender -> "gender"
* dateOfBirth -> "date_of_birth"
* name -> "name"
