// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Deployment.json. Do not edit: change the source or the generator.

Logical: Deployment
Id: Deployment
Title: "Deployment"
Description: "The iHRIS 4.3.3 form class `iHRIS_Deployment` (forms: deployment; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_Deployment."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Deployment"
* ^version = "4.3.3"
* ^status = #draft
* healthFacility 1..1 Coding "Health Facility"
* healthFacility from https://litlfred.github.io/ihris/dak/ValueSet/health_facility (extensible)
* jobTitle 0..1 string "Job/Post Title"
* jobCode 0..1 string "Job/Post Code"
* deploymentDate 1..1 date "Deployment Date"

Mapping: Deployment-I2CE
Id: i2ce
Source: Deployment
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Deployment"
* -> "iHRIS_Deployment"
* healthFacility -> "health_facility"
* jobTitle -> "job_title"
* jobCode -> "job_code"
* deploymentDate -> "deployment_date"
