// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/DisciplinaryAction.json. Do not edit: change the source or the generator.

Logical: DisciplinaryAction
Id: DisciplinaryAction
Title: "Disciplinary Action"
Description: "The iHRIS 4.3.3 form class `iHRIS_DisciplinaryAction` (forms: disciplinary_action; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_DisciplinaryAction, ihris-qualify/form-class/iHRIS_DisciplinaryAction."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/DisciplinaryAction"
* ^version = "4.3.3"
* ^status = #draft
* actionDate 1..1 date "Date of Discussion"
* disciplinaryActionType 1..1 Coding "Action Taken"
* disciplinaryActionType from https://litlfred.github.io/ihris/dak/ValueSet/disciplinary_action_type (extensible)
* disciplinaryActionReason 1..1 Coding "Reason for Action"
* disciplinaryActionReason from https://litlfred.github.io/ihris/dak/ValueSet/disciplinary_action_reason (extensible)
* startDate 1..1 date "Start of Applicability"
* endDate 0..1 date "End of Applicability"
* notes 0..1 string "Notes"
* personsPresent 0..1 string "People Present"
* suspend 0..1 boolean "Suspend License?"
* reinstateDate 0..1 date "Reinstatement Date"

Mapping: DisciplinaryAction-I2CE
Id: i2ce
Source: DisciplinaryAction
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_DisciplinaryAction"
* -> "iHRIS_DisciplinaryAction"
* actionDate -> "action_date"
* disciplinaryActionType -> "disciplinary_action_type"
* disciplinaryActionReason -> "disciplinary_action_reason"
* startDate -> "start_date"
* endDate -> "end_date"
* notes -> "notes"
* personsPresent -> "persons_present"
* suspend -> "suspend"
* reinstateDate -> "reinstate_date"
