// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Document.json. Do not edit: change the source or the generator.

Logical: Document
Id: Document
Title: "Person Resume"
Description: "The iHRIS 4.3.3 form class `iHRIS_Document` (forms: person_resume; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Document."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Document"
* ^version = "4.3.3"
* ^status = #draft
* document 0..1 Attachment "Document"
* date 1..1 date "Date"
* description 0..1 string "Description"

Mapping: Document-I2CE
Id: i2ce
Source: Document
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Document"
* -> "iHRIS_Document"
* document -> "document"
* date -> "date"
* description -> "description"
