// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Education.json. Do not edit: change the source or the generator.

Logical: Education
Id: Education
Title: "Education History"
Description: "The iHRIS 4.3.3 form class `iHRIS_Education` (forms: education; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Education."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Education"
* ^version = "4.3.3"
* ^status = #draft
* degree 1..1 Coding "Degree"
* degree from https://litlfred.github.io/ihris/dak/ValueSet/degree (extensible)
* institution 1..1 string "Institution Name"
* location 0..1 string "Institution Location"
* year 0..1 date "Year of Graduation (leave blank if In Progress)"
* major 0..1 string "Major"

Mapping: Education-I2CE
Id: i2ce
Source: Education
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Education"
* -> "iHRIS_Education"
* degree -> "degree"
* institution -> "institution"
* location -> "location"
* year -> "year"
* major -> "major"
