// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Employment.json. Do not edit: change the source or the generator.

Logical: Employment
Id: Employment
Title: "Employment History"
Description: "The iHRIS 4.3.3 form class `iHRIS_Employment` (forms: employment; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Employment."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Employment"
* ^version = "4.3.3"
* ^status = #draft
* companyName 1..1 string "Company Name"
* companyAddress 0..1 string "Company Address"
* companyPhone 0..1 string "Company Telephone"
* startDate 1..1 date "Date Started"
* startWage 0..1 Money "Starting Wage"
* startPosition 0..1 string "Starting Position"
* endDate 0..1 date "Date Ended (leave blank if still employed)"
* endWage 0..1 Money "Ending Wage"
* endPosition 0..1 string "Ending Position"
* supervisor 0..1 string "Supervisor"
* contactOk 0..1 boolean "Ok to Contact?"
* responsibilities 0..1 string "Job Responsibilities"
* reasonForLeaving 0..1 string "Reason for Leaving"

Mapping: Employment-I2CE
Id: i2ce
Source: Employment
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Employment"
* -> "iHRIS_Employment"
* companyName -> "company_name"
* companyAddress -> "company_address"
* companyPhone -> "company_phone"
* startDate -> "start_date"
* startWage -> "start_wage"
* startPosition -> "start_position"
* endDate -> "end_date"
* endWage -> "end_wage"
* endPosition -> "end_position"
* supervisor -> "supervisor"
* contactOk -> "contact_ok"
* responsibilities -> "responsibilities"
* reasonForLeaving -> "reason_for_leaving"
