// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Exam.json. Do not edit: change the source or the generator.

Logical: Exam
Id: Exam
Title: "Exam"
Description: "The iHRIS 4.3.3 form class `iHRIS_Exam` (forms: exam; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_Exam."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Exam"
* ^version = "4.3.3"
* ^status = #draft
* applicationDate 1..1 date "Application Date"
* materialsReceived 0..1 boolean "Materials Received?"
* materialsApproved 0..1 boolean "Materials Approved?"
* endorserName 0..1 string "Endorser Name"
* endorserDate 0..1 date "Endorser Date"
* endorserQualifications 0..1 string "Endorser Qualifications"
* examDate 0..1 date "Exam Date"
* try 0..1 Coding "Exam Try"
* try from https://litlfred.github.io/ihris/dak/ValueSet/exam_try (extensible)
* results 0..1 Coding "Exam Results"
* results from https://litlfred.github.io/ihris/dak/ValueSet/exam_result (extensible)
* examNumber 0..1 string "Exam Number"

Mapping: Exam-I2CE
Id: i2ce
Source: Exam
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Exam"
* -> "iHRIS_Exam"
* applicationDate -> "application_date"
* materialsReceived -> "materials_received"
* materialsApproved -> "materials_approved"
* endorserName -> "endorser_name"
* endorserDate -> "endorser_date"
* endorserQualifications -> "endorser_qualifications"
* examDate -> "exam_date"
* try -> "try"
* results -> "results"
* examNumber -> "exam_number"
