// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/FacilityInstitutionEditFacility.json. Do not edit: change the source or the generator.

Logical: FacilityInstitutionEditFacility
Id: FacilityInstitutionEditFacility
Title: "Edit Facility to Link Facilities with Institutions"
Description: "The iHRIS 4.3.3 form class `iHRIS_FacilityInstitutionEditFacility` (forms: facility_institution_edit_fac; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_FacilityInstitutionEditFacility."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/FacilityInstitutionEditFacility"
* ^version = "4.3.3"
* ^status = #draft
* healthFacility 1..1 Coding "Health Facility"
* healthFacility from https://litlfred.github.io/ihris/dak/ValueSet/health_facility (extensible)
* trainingInstitution 1..* Coding "Training Institution"
* trainingInstitution from https://litlfred.github.io/ihris/dak/ValueSet/training_institution (extensible)

Mapping: FacilityInstitutionEditFacility-I2CE
Id: i2ce
Source: FacilityInstitutionEditFacility
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_FacilityInstitutionEditFacility"
* -> "iHRIS_FacilityInstitutionEditFacility"
* healthFacility -> "health_facility"
* trainingInstitution -> "training_institution"
