// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/FacilityInstitutionEditInstitution.json. Do not edit: change the source or the generator.

Logical: FacilityInstitutionEditInstitution
Id: FacilityInstitutionEditInstitution
Title: "Edit Institution to Link Facilities and Institutions"
Description: "The iHRIS 4.3.3 form class `iHRIS_FacilityInstitutionEditInstitution` (forms: facility_institution_edit_inst; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_FacilityInstitutionEditInstitution."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/FacilityInstitutionEditInstitution"
* ^version = "4.3.3"
* ^status = #draft
* healthFacility 1..* Coding "Health Facility"
* healthFacility from https://litlfred.github.io/ihris/dak/ValueSet/health_facility (extensible)
* trainingInstitution 1..1 Coding "Training Institution"
* trainingInstitution from https://litlfred.github.io/ihris/dak/ValueSet/training_institution (extensible)

Mapping: FacilityInstitutionEditInstitution-I2CE
Id: i2ce
Source: FacilityInstitutionEditInstitution
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_FacilityInstitutionEditInstitution"
* -> "iHRIS_FacilityInstitutionEditInstitution"
* healthFacility -> "health_facility"
* trainingInstitution -> "training_institution"
