// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/FacilityInstitution.json. Do not edit: change the source or the generator.

Logical: FacilityInstitution
Id: FacilityInstitution
Title: "Facility Institution"
Description: "The iHRIS 4.3.3 form class `iHRIS_FacilityInstitution` (forms: facility_institution; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_FacilityInstitution."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/FacilityInstitution"
* ^version = "4.3.3"
* ^status = #draft
* healthFacility 1..1 Coding "Health Facility"
* healthFacility from https://litlfred.github.io/ihris/dak/ValueSet/health_facility (extensible)
* trainingInstitution 1..1 Coding "Training Institution"
* trainingInstitution from https://litlfred.github.io/ihris/dak/ValueSet/training_institution (extensible)
* active 1..1 boolean "Active?"

Mapping: FacilityInstitution-I2CE
Id: i2ce
Source: FacilityInstitution
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_FacilityInstitution"
* -> "iHRIS_FacilityInstitution"
* healthFacility -> "health_facility"
* trainingInstitution -> "training_institution"
* active -> "active"
