// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/InstitutionInspection.json. Do not edit: change the source or the generator.

Logical: InstitutionInspection
Id: InstitutionInspection
Title: "Institution Inspection"
Description: "The iHRIS 4.3.3 form class `iHRIS_InstitutionInspection` (forms: institution_inspection; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_InstitutionInspection."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/InstitutionInspection"
* ^version = "4.3.3"
* ^status = #draft
* date 1..1 date "Inspection Date"
* notes 0..1 string "Notes"
* pass 0..1 boolean "Passed?"

Mapping: InstitutionInspection-I2CE
Id: i2ce
Source: InstitutionInspection
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_InstitutionInspection"
* -> "iHRIS_InstitutionInspection"
* date -> "date"
* notes -> "notes"
* pass -> "pass"
