// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/LeaveOfAbsence.json. Do not edit: change the source or the generator.

Logical: LeaveOfAbsence
Id: LeaveOfAbsence
Title: "Leave Of Absence"
Description: "The iHRIS 4.3.3 form class `iHRIS_LeaveOfAbsence` (forms: leave_of_absence; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_LeaveOfAbsence."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/LeaveOfAbsence"
* ^version = "4.3.3"
* ^status = #draft
* type 1..1 Coding "Absence Type"
* startDate 1..1 date "Start Date"
* endDate 0..1 date "End Date"
* paid 0..1 boolean "Paid?"
* incomplete 0..1 boolean "Training incomplete? (for education)"
* cause 0..1 string "Cause / Diagnosis (for health)"
* notes 0..1 string "Notes"

Mapping: LeaveOfAbsence-I2CE
Id: i2ce
Source: LeaveOfAbsence
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_LeaveOfAbsence"
* -> "iHRIS_LeaveOfAbsence"
* type -> "type"
* startDate -> "start_date"
* endDate -> "end_date"
* paid -> "paid"
* incomplete -> "incomplete"
* cause -> "cause"
* notes -> "notes"
