// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/LeaveRequest.json. Do not edit: change the source or the generator.

Logical: LeaveRequest
Id: LeaveRequest
Title: "Leave Request"
Description: "The iHRIS 4.3.3 form class `iHRIS_LeaveRequest` (forms: leave_request; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_LeaveRequest."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/LeaveRequest"
* ^version = "4.3.3"
* ^status = #draft
* notes 0..1 string "Notes"
* leaveCategory 1..1 Coding "Leave Category"
* leaveCategory from https://litlfred.github.io/ihris/dak/ValueSet/leave_category (extensible)
* leaveStatus 0..1 Coding "Leave Status"
* leaveStatus from https://litlfred.github.io/ihris/dak/ValueSet/leave_status (extensible)
* supervisorApproval 0..1 boolean "Supervisor Approval"
* hrApproval 0..1 boolean "Human Resource Approval"
* startDate 1..1 date "Leave Start Date"
* endDate 1..1 date "Leave End Date"
* leaveDays 0..1 integer "Leave Days"
* returnDate 1..1 date "Return Date"
* approvedReturnDate 0..1 date "Approved Return Date"

Mapping: LeaveRequest-I2CE
Id: i2ce
Source: LeaveRequest
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_LeaveRequest"
* -> "iHRIS_LeaveRequest"
* notes -> "notes"
* leaveCategory -> "leave_category"
* leaveStatus -> "leave_status"
* supervisorApproval -> "supervisor_approval"
* hrApproval -> "hr_approval"
* startDate -> "start_date"
* endDate -> "end_date"
* leaveDays -> "leave_days"
* returnDate -> "return_date"
* approvedReturnDate -> "approved_return_date"
