// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/License.json. Do not edit: change the source or the generator.

Logical: License
Id: License
Title: "License"
Description: "The iHRIS 4.3.3 form class `iHRIS_License` (forms: license; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_License."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/License"
* ^version = "4.3.3"
* ^status = #draft
* licenseNumber 1..1 Identifier "License Number"
* startDate 1..1 date "Start Date"
* endDate 1..1 date "End Date"
* suspend 0..1 boolean "Suspended?"

Mapping: License-I2CE
Id: i2ce
Source: License
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_License"
* -> "iHRIS_License"
* licenseNumber -> "license_number"
* startDate -> "start_date"
* endDate -> "end_date"
* suspend -> "suspend"
