// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/ManageDemographic.json. Do not edit: change the source or the generator.

Logical: ManageDemographic
Id: ManageDemographic
Title: "Demographic Information"
Description: "The iHRIS 4.3.3 form class `iHRIS_ManageDemographic` (forms: demographic; extends `iHRIS_Demographic`), as a logical model. Derived from ihris-manage/form-class/iHRIS_ManageDemographic."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/ManageDemographic"
* ^version = "4.3.3"
* ^status = #draft
* dependents 0..1 integer "Number of Dependents"

Mapping: ManageDemographic-I2CE
Id: i2ce
Source: ManageDemographic
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_ManageDemographic"
* -> "iHRIS_ManageDemographic"
* dependents -> "dependents"
