// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/ManagePerson.json. Do not edit: change the source or the generator.

Logical: ManagePerson
Id: ManagePerson
Title: "Person"
Description: "The iHRIS 4.3.3 form class `iHRIS_ManagePerson` (forms: person; extends `iHRIS_Person`), as a logical model. Derived from ihris-manage/form-class/iHRIS_ManagePerson."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/ManagePerson"
* ^version = "4.3.3"
* ^status = #draft

Mapping: ManagePerson-I2CE
Id: i2ce
Source: ManagePerson
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_ManagePerson"
* -> "iHRIS_ManagePerson"
