// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/NamedContact.json. Do not edit: change the source or the generator.

Logical: NamedContact
Id: NamedContact
Title: "Emergency Contact"
Description: "The iHRIS 4.3.3 form class `iHRIS_NamedContact` (forms: person_contact_emergency; extends `iHRIS_Contact`), as a logical model. Derived from ihris-common/form-class/iHRIS_NamedContact."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/NamedContact"
* ^version = "4.3.3"
* ^status = #draft
* name 0..1 string "Name"

Mapping: NamedContact-I2CE
Id: i2ce
Source: NamedContact
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_NamedContact"
* -> "iHRIS_NamedContact"
* name -> "name"
