// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/NextOfKin.json. Do not edit: change the source or the generator.

Logical: NextOfKin
Id: NextOfKin
Title: "Next of Kin"
Description: "The iHRIS 4.3.3 form class `iHRIS_NextOfKin` (forms: nextofkin; extends `iHRIS_Contact`), as a logical model. Derived from ihris-common/form-class/iHRIS_NextOfKin."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/NextOfKin"
* ^version = "4.3.3"
* ^status = #draft
* name 1..1 string "Name"
* relationship 1..1 string "Relationship"

Mapping: NextOfKin-I2CE
Id: i2ce
Source: NextOfKin
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_NextOfKin"
* -> "iHRIS_NextOfKin"
* name -> "name"
* relationship -> "relationship"
