// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Notes.json. Do not edit: change the source or the generator.

Logical: Notes
Id: Notes
Title: "Notes"
Description: "The iHRIS 4.3.3 form class `iHRIS_Notes` (forms: notes; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Notes."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Notes"
* ^version = "4.3.3"
* ^status = #draft
* note 1..1 string "Note"
* dateAdded 1..1 date "Date Added"

Mapping: Notes-I2CE
Id: i2ce
Source: Notes
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Notes"
* -> "iHRIS_Notes"
* note -> "note"
* dateAdded -> "date_added"
