// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/OutMigration.json. Do not edit: change the source or the generator.

Logical: OutMigration
Id: OutMigration
Title: "Out Migration"
Description: "The iHRIS 4.3.3 form class `iHRIS_OutMigration` (forms: out_migration; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_OutMigration."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/OutMigration"
* ^version = "4.3.3"
* ^status = #draft
* country 1..1 Coding "Country"
* country from https://litlfred.github.io/ihris/dak/ValueSet/country (extensible)
* newAddress 0..1 string "Address in new Country"
* outMigrationReason 1..1 Coding "Out Migration Reason"
* outMigrationReason from https://litlfred.github.io/ihris/dak/ValueSet/out_migration_reason (extensible)
* organization 0..1 string "Organization Requesting Verification"
* requestDate 0..1 date "Request Date"

Mapping: OutMigration-I2CE
Id: i2ce
Source: OutMigration
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_OutMigration"
* -> "iHRIS_OutMigration"
* country -> "country"
* newAddress -> "new_address"
* outMigrationReason -> "out_migration_reason"
* organization -> "organization"
* requestDate -> "request_date"
