// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PersonPosition.json. Do not edit: change the source or the generator.

Logical: PersonPosition
Id: PersonPosition
Title: "Person Position"
Description: "The iHRIS 4.3.3 form class `iHRIS_PersonPosition` (forms: person_position; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_PersonPosition."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PersonPosition"
* ^version = "4.3.3"
* ^status = #draft
* position 1..1 Coding "Position"
* position from https://litlfred.github.io/ihris/dak/ValueSet/position (extensible)
* startDate 1..1 date "Start Date"
* endDate 0..1 date "End Date"
* reason 0..1 Coding "Reason for Departure"
* reason from https://litlfred.github.io/ihris/dak/ValueSet/pos_change_reason (extensible)

Mapping: PersonPosition-I2CE
Id: i2ce
Source: PersonPosition
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PersonPosition"
* -> "iHRIS_PersonPosition"
* position -> "position"
* startDate -> "start_date"
* endDate -> "end_date"
* reason -> "reason"
