// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PersonID.json. Do not edit: change the source or the generator.

Logical: PersonID
Id: PersonID
Title: "Person Identification"
Description: "The iHRIS 4.3.3 form class `iHRIS_PersonID` (forms: person_id; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_PersonID."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PersonID"
* ^version = "4.3.3"
* ^status = #draft
* idType 1..1 Coding "Identification Type"
* idType from https://litlfred.github.io/ihris/dak/ValueSet/id_type (extensible)
* idNum 1..1 string "Identification Number"
* issueDate 0..1 date "Date of Issue"
* expirationDate 0..1 date "Date of Expiration"
* country 0..1 Coding "Country of Issue"
* country from https://litlfred.github.io/ihris/dak/ValueSet/country (extensible)
* place 0..1 string "Place of Issue"

Mapping: PersonID-I2CE
Id: i2ce
Source: PersonID
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PersonID"
* -> "iHRIS_PersonID"
* idType -> "id_type"
* idNum -> "id_num"
* issueDate -> "issue_date"
* expirationDate -> "expiration_date"
* country -> "country"
* place -> "place"
