// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PersonReference.json. Do not edit: change the source or the generator.

Logical: PersonReference
Id: PersonReference
Title: "Personal Reference"
Description: "The iHRIS 4.3.3 form class `iHRIS_PersonReference` (forms: person_reference; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_PersonReference."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PersonReference"
* ^version = "4.3.3"
* ^status = #draft
* surname 1..1 string "Surname"
* firstname 1..1 string "First Name"
* phone 0..1 string "Phone"
* mobile 0..1 string "Mobile Phone"
* address 0..1 string "Address"
* howLong 0..1 string "How long have you known this person?"

Mapping: PersonReference-I2CE
Id: i2ce
Source: PersonReference
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PersonReference"
* -> "iHRIS_PersonReference"
* surname -> "surname"
* firstname -> "firstname"
* phone -> "phone"
* mobile -> "mobile"
* address -> "address"
* howLong -> "how_long"
