// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PersonTraining.json. Do not edit: change the source or the generator.

Logical: PersonTraining
Id: PersonTraining
Title: "Continuing Education"
Description: "The iHRIS 4.3.3 form class `iHRIS_PersonTraining` (forms: person_training; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_PersonTraining."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PersonTraining"
* ^version = "4.3.3"
* ^status = #draft
* startDate 1..1 date "Start Date"
* endDate 0..1 date "End Date"
* training 1..1 string "Training Course"
* provider 0..1 string "Training Provider"
* location 0..1 string "Training Location"
* cpdCredit 1..1 string "CPD Credit"

Mapping: PersonTraining-I2CE
Id: i2ce
Source: PersonTraining
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PersonTraining"
* -> "iHRIS_PersonTraining"
* startDate -> "start_date"
* endDate -> "end_date"
* training -> "training"
* provider -> "provider"
* location -> "location"
* cpdCredit -> "cpd_credit"
