// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PersonCompetency.json. Do not edit: change the source or the generator.

Logical: PersonCompetency
Id: PersonCompetency
Title: "Person Competency"
Description: "The iHRIS 4.3.3 form class `iHRIS_PersonCompetency` (forms: person_competency; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_PersonCompetency."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PersonCompetency"
* ^version = "4.3.3"
* ^status = #draft
* evaluationDate 0..1 date "Last Evaluated"
* competencyEvaluation 0..1 Coding "Evaluation"
* competencyEvaluation from https://litlfred.github.io/ihris/dak/ValueSet/competency_evaluation (extensible)
* competency 1..1 Coding "Competency"
* competency from https://litlfred.github.io/ihris/dak/ValueSet/competency (extensible)

Mapping: PersonCompetency-I2CE
Id: i2ce
Source: PersonCompetency
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PersonCompetency"
* -> "iHRIS_PersonCompetency"
* evaluationDate -> "evaluation_date"
* competencyEvaluation -> "competency_evaluation"
* competency -> "competency"
