// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Person.json. Do not edit: change the source or the generator.

Logical: Person
Id: Person
Title: "Person"
Description: "The iHRIS 4.3.3 form class `iHRIS_Person` (forms: person; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Person."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Person"
* ^version = "4.3.3"
* ^status = #draft
* surname 1..1 string "Surname"
* firstname 1..1 string "First Name"
* othername 0..1 string "Other Names"
* nationality 1..1 Coding "Nationality"
* nationality from https://litlfred.github.io/ihris/dak/ValueSet/country (extensible)
* surnameIgnore 0..1 boolean "surname ignore"
* residence 1..1 Coding "Residence"
* residence from https://litlfred.github.io/ihris/dak/ValueSet/country (extensible)
* residence from https://litlfred.github.io/ihris/dak/ValueSet/county (extensible)
* residence from https://litlfred.github.io/ihris/dak/ValueSet/district (extensible)
* residence from https://litlfred.github.io/ihris/dak/ValueSet/region (extensible)

Mapping: Person-I2CE
Id: i2ce
Source: Person
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Person"
* -> "iHRIS_Person"
* surname -> "surname"
* firstname -> "firstname"
* othername -> "othername"
* nationality -> "nationality"
* surnameIgnore -> "surname_ignore"
* residence -> "residence"
