// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Person_Scheduled_Training_Course.json. Do not edit: change the source or the generator.

Logical: Person_Scheduled_Training_Course
Id: Person-Scheduled-Training-Course
Title: "Person Scheduled Training Course"
Description: "The iHRIS 4.3.3 form class `iHRIS_Person_Scheduled_Training_Course` (forms: person_scheduled_training_course; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Person_Scheduled_Training_Course."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Person_Scheduled_Training_Course"
* ^version = "4.3.3"
* ^status = #draft
* trainingCourseMod 0..* Coding "Modules"
* trainingCourseMod from https://litlfred.github.io/ihris/dak/ValueSet/training_course_mod (extensible)
* certificationDate 0..1 date "Certification Date"
* attending 0..1 boolean "Is Attending"
* isRetraining 0..1 boolean "Retraining"
* completed 0..1 boolean "Completed"
* dutyCommencementDate 0..1 date "Duty Commencement"
* requestDate 1..1 date "Request Date"
* notes 0..1 string "Notes"
* average 0..1 integer "Average"
* trainingCourseEvaluation 1..1 Coding "Evaluation"
* trainingCourseEvaluation from https://litlfred.github.io/ihris/dak/ValueSet/training_course_evaluation (extensible)
* trainingCourseRequestor 0..1 Coding "Requested By"
* trainingCourseRequestor from https://litlfred.github.io/ihris/dak/ValueSet/training_course_requestor (extensible)
* scheduledTrainingCourse 1..1 Coding "Instance"
* scheduledTrainingCourse from https://litlfred.github.io/ihris/dak/ValueSet/scheduled_training_course (extensible)

Mapping: Person_Scheduled_Training_Course-I2CE
Id: i2ce
Source: Person_Scheduled_Training_Course
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Person_Scheduled_Training_Course"
* -> "iHRIS_Person_Scheduled_Training_Course"
* trainingCourseMod -> "training_course_mod"
* certificationDate -> "certification_date"
* attending -> "attending"
* isRetraining -> "is_retraining"
* completed -> "completed"
* dutyCommencementDate -> "duty_commencement_date"
* requestDate -> "request_date"
* notes -> "notes"
* average -> "average"
* trainingCourseEvaluation -> "training_course_evaluation"
* trainingCourseRequestor -> "training_course_requestor"
* scheduledTrainingCourse -> "scheduled_training_course"
