// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PersonLanguage.json. Do not edit: change the source or the generator.

Logical: PersonLanguage
Id: PersonLanguage
Title: "Person Language Proficiency"
Description: "The iHRIS 4.3.3 form class `iHRIS_PersonLanguage` (forms: person_language; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_PersonLanguage."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PersonLanguage"
* ^version = "4.3.3"
* ^status = #draft
* language 1..1 Coding "Language"
* language from https://litlfred.github.io/ihris/dak/ValueSet/language (extensible)
* speaking 1..1 Coding "Speaking Proficiency"
* speaking from https://litlfred.github.io/ihris/dak/ValueSet/language_proficiency (extensible)
* reading 1..1 Coding "Reading Proficiency"
* reading from https://litlfred.github.io/ihris/dak/ValueSet/language_proficiency (extensible)
* writing 1..1 Coding "Writing Proficiency"
* writing from https://litlfred.github.io/ihris/dak/ValueSet/language_proficiency (extensible)

Mapping: PersonLanguage-I2CE
Id: i2ce
Source: PersonLanguage
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PersonLanguage"
* -> "iHRIS_PersonLanguage"
* language -> "language"
* speaking -> "speaking"
* reading -> "reading"
* writing -> "writing"
