// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Person_Record_Status.json. Do not edit: change the source or the generator.

Logical: Person_Record_Status
Id: Person-Record-Status
Title: "Person Record Status"
Description: "The iHRIS 4.3.3 form class `iHRIS_Person_Record_Status` (forms: person_record_status; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Person_Record_Status."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Person_Record_Status"
* ^version = "4.3.3"
* ^status = #draft
* duplicate 0..1 boolean "Duplicate"
* incomplete 0..1 boolean "Incomplete"
* incorrect 0..1 boolean "Incorrect"
* comment 0..1 string "Comments"

Mapping: Person_Record_Status-I2CE
Id: i2ce
Source: Person_Record_Status
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Person_Record_Status"
* -> "iHRIS_Person_Record_Status"
* duplicate -> "duplicate"
* incomplete -> "incomplete"
* incorrect -> "incorrect"
* comment -> "comment"
