// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PersonAttendance.json. Do not edit: change the source or the generator.

Logical: PersonAttendance
Id: PersonAttendance
Title: "Attendance Information"
Description: "The iHRIS 4.3.3 form class `iHRIS_PersonAttendance` (forms: person_attendance; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_PersonAttendance."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PersonAttendance"
* ^version = "4.3.3"
* ^status = #draft
* monthYear 1..1 date "Month and Year"
* daysPresent 1..1 integer "Total Number of Days Present"
* daysOffRequest 1..1 integer "Total Number of Days of Special Request Absence"
* daysOffDuty 1..1 integer "Total Number of Days Off Duty"
* daysLeave 1..1 integer "Total Number of Days on Leave"
* position 0..1 Coding "Current Position"
* position from https://litlfred.github.io/ihris/dak/ValueSet/position (extensible)
* daysAbsent 0..1 integer "Total Number of Days Absent"
* absenteeismRate 0..1 integer "Absenteeism Rate"
* monthYearDay 0..1 date "Month Year Day"

Mapping: PersonAttendance-I2CE
Id: i2ce
Source: PersonAttendance
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PersonAttendance"
* -> "iHRIS_PersonAttendance"
* monthYear -> "month_year"
* daysPresent -> "days_present"
* daysOffRequest -> "days_off_request"
* daysOffDuty -> "days_off_duty"
* daysLeave -> "days_leave"
* position -> "position"
* daysAbsent -> "days_absent"
* absenteeismRate -> "absenteeism_rate"
* monthYearDay -> "month_year_day"
