// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Photo.json. Do not edit: change the source or the generator.

Logical: Photo
Id: Photo
Title: "Person Photo"
Description: "The iHRIS 4.3.3 form class `iHRIS_Photo` (forms: person_photo_passport; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Photo."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Photo"
* ^version = "4.3.3"
* ^status = #draft
* image 0..1 Attachment "Image"
* date 1..1 date "Date"
* description 0..1 string "Description"

Mapping: Photo-I2CE
Id: i2ce
Source: Photo
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Photo"
* -> "iHRIS_Photo"
* image -> "image"
* date -> "date"
* description -> "description"
