// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PositionInterview.json. Do not edit: change the source or the generator.

Logical: PositionInterview
Id: PositionInterview
Title: "Position Interview"
Description: "The iHRIS 4.3.3 form class `iHRIS_PositionInterview` (forms: position_interview; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_PositionInterview."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PositionInterview"
* ^version = "4.3.3"
* ^status = #draft
* date 1..1 date "Date of Interview"
* person 1..1 string "People Attending"
* comments 0..1 string "Comments"
* record 0..1 Attachment "Interview Record"

Mapping: PositionInterview-I2CE
Id: i2ce
Source: PositionInterview
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PositionInterview"
* -> "iHRIS_PositionInterview"
* date -> "date"
* person -> "person"
* comments -> "comments"
* record -> "record"
