// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PositionDecision.json. Do not edit: change the source or the generator.

Logical: PositionDecision
Id: PositionDecision
Title: "Position Decision"
Description: "The iHRIS 4.3.3 form class `iHRIS_PositionDecision` (forms: position_decision; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_PositionDecision."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PositionDecision"
* ^version = "4.3.3"
* ^status = #draft
* date 1..1 date "Date of Decision"
* offer 0..1 boolean "Make a Job Offer?"
* comments 0..1 string "Comments"
* record 0..1 Attachment "Record of Decision"

Mapping: PositionDecision-I2CE
Id: i2ce
Source: PositionDecision
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PositionDecision"
* -> "iHRIS_PositionDecision"
* date -> "date"
* offer -> "offer"
* comments -> "comments"
* record -> "record"
