// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/PrivatePractice.json. Do not edit: change the source or the generator.

Logical: PrivatePractice
Id: PrivatePractice
Title: "Private Practice License"
Description: "The iHRIS 4.3.3 form class `iHRIS_PrivatePractice` (forms: private_practice; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_PrivatePractice."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/PrivatePractice"
* ^version = "4.3.3"
* ^status = #draft
* licenseNumber 1..1 Identifier "License Number"
* startDate 1..1 date "Start Date"
* endDate 1..1 date "End Date"
* inspectionResults 0..1 string "Inspection Results"
* inspectionDate 0..1 date "Inspection Date"
* healthFacility 1..1 Coding "Health Facility"
* healthFacility from https://litlfred.github.io/ihris/dak/ValueSet/health_facility (extensible)

Mapping: PrivatePractice-I2CE
Id: i2ce
Source: PrivatePractice
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_PrivatePractice"
* -> "iHRIS_PrivatePractice"
* licenseNumber -> "license_number"
* startDate -> "start_date"
* endDate -> "end_date"
* inspectionResults -> "inspection_results"
* inspectionDate -> "inspection_date"
* healthFacility -> "health_facility"
