// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/QualifyPerson.json. Do not edit: change the source or the generator.

Logical: QualifyPerson
Id: QualifyPerson
Title: "Person"
Description: "The iHRIS 4.3.3 form class `iHRIS_QualifyPerson` (forms: person; extends `iHRIS_Person`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_QualifyPerson."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/QualifyPerson"
* ^version = "4.3.3"
* ^status = #draft
* home 0..1 Coding "Home"
* home from https://litlfred.github.io/ihris/dak/ValueSet/county (extensible)
* home from https://litlfred.github.io/ihris/dak/ValueSet/district (extensible)

Mapping: QualifyPerson-I2CE
Id: i2ce
Source: QualifyPerson
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_QualifyPerson"
* -> "iHRIS_QualifyPerson"
* home -> "home"
