// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/QualifyDemographic.json. Do not edit: change the source or the generator.

Logical: QualifyDemographic
Id: QualifyDemographic
Title: "Demographic Information"
Description: "The iHRIS 4.3.3 form class `iHRIS_QualifyDemographic` (forms: demographic; extends `iHRIS_Demographic`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_QualifyDemographic."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/QualifyDemographic"
* ^version = "4.3.3"
* ^status = #draft
* birthLocation 0..1 Coding "Birth Location"
* birthLocation from https://litlfred.github.io/ihris/dak/ValueSet/county (extensible)
* birthLocation from https://litlfred.github.io/ihris/dak/ValueSet/district (extensible)

Mapping: QualifyDemographic-I2CE
Id: i2ce
Source: QualifyDemographic
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_QualifyDemographic"
* -> "iHRIS_QualifyDemographic"
* birthLocation -> "birth_location"
