// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/RecordVerify.json. Do not edit: change the source or the generator.

Logical: RecordVerify
Id: RecordVerify
Title: "Record Verification"
Description: "The iHRIS 4.3.3 form class `iHRIS_RecordVerify` (forms: record_verify; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_RecordVerify."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/RecordVerify"
* ^version = "4.3.3"
* ^status = #draft
* verifyDate 0..1 date "Verification Date"
* verifyChange 0..* Coding "Changes Made"
* verifyChange from https://litlfred.github.io/ihris/dak/ValueSet/verify_change (extensible)

Mapping: RecordVerify-I2CE
Id: i2ce
Source: RecordVerify
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_RecordVerify"
* -> "iHRIS_RecordVerify"
* verifyDate -> "verify_date"
* verifyChange -> "verify_change"
