// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Registration.json. Do not edit: change the source or the generator.

Logical: Registration
Id: Registration
Title: "Registration"
Description: "The iHRIS 4.3.3 form class `iHRIS_Registration` (forms: registration; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Registration, ihris-qualify/form-class/iHRIS_Registration."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Registration"
* ^version = "4.3.3"
* ^status = #draft
* council 1..1 Coding "Registration Council"
* council from https://litlfred.github.io/ihris/dak/ValueSet/council (extensible)
* registrationNumber 1..1 string "Registration Number"
* licenseNumber 0..1 string "License Number"
* registrationDate 1..1 date "Registration Date"
* licenseExpiration 0..1 date "License Expiration Date"
* applicationDate 1..1 date "Application Date"
* practiceType 1..1 Coding "Practice Type"
* practiceType from https://litlfred.github.io/ihris/dak/ValueSet/registration_type (extensible)

Mapping: Registration-I2CE
Id: i2ce
Source: Registration
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Registration"
* -> "iHRIS_Registration"
* council -> "council"
* registrationNumber -> "registration_number"
* licenseNumber -> "license_number"
* registrationDate -> "registration_date"
* licenseExpiration -> "license_expiration"
* applicationDate -> "application_date"
* practiceType -> "practice_type"
