// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Salary.json. Do not edit: change the source or the generator.

Logical: Salary
Id: Salary
Title: "Salary"
Description: "The iHRIS 4.3.3 form class `iHRIS_Salary` (forms: salary; extends `I2CE_Form`), as a logical model. Derived from ihris-manage/form-class/iHRIS_Salary."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Salary"
* ^version = "4.3.3"
* ^status = #draft
* startDate 1..1 date "Start Date"
* salary 1..1 Money "Salary"
* endDate 0..1 date "End Date"
* last 0..1 integer "last"
* notes 0..1 string "Notes"

Mapping: Salary-I2CE
Id: i2ce
Source: Salary
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Salary"
* -> "iHRIS_Salary"
* startDate -> "start_date"
* salary -> "salary"
* endDate -> "end_date"
* last -> "last"
* notes -> "notes"
