// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/SecondaryEducation.json. Do not edit: change the source or the generator.

Logical: SecondaryEducation
Id: SecondaryEducation
Title: "Education History"
Description: "The iHRIS 4.3.3 form class `iHRIS_SecondaryEducation` (forms: education; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_SecondaryEducation."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/SecondaryEducation"
* ^version = "4.3.3"
* ^status = #draft
* secSchool 1..1 string "Secondary School Name"
* certificate 1..1 Coding "Certificate"
* certificate from https://litlfred.github.io/ihris/dak/ValueSet/certificate (extensible)
* grade 0..1 string "Grade Obtained"
* certificateNumber 0..1 string "Certificate Number"

Mapping: SecondaryEducation-I2CE
Id: i2ce
Source: SecondaryEducation
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_SecondaryEducation"
* -> "iHRIS_SecondaryEducation"
* secSchool -> "sec_school"
* certificate -> "certificate"
* grade -> "grade"
* certificateNumber -> "certificate_number"
