// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Training.json. Do not edit: change the source or the generator.

Logical: Training
Id: Training
Title: "Training"
Description: "The iHRIS 4.3.3 form class `iHRIS_Training` (forms: training; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_Training."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Training"
* ^version = "4.3.3"
* ^status = #draft
* indexNum 1..1 Identifier "Index Number"
* cadre 0..1 Coding "Cadre"
* cadre from https://litlfred.github.io/ihris/dak/ValueSet/cadre (extensible)
* intakeDate 1..1 date "Intake Date"
* graduation 0..1 date "Graduation Date"
* trainedOutside 0..1 boolean "Trained Outside this Country"
* trainingProgram 0..1 Coding "Training Program"
* trainingProgram from https://litlfred.github.io/ihris/dak/ValueSet/training_program (extensible)
* trainingInstitution 0..1 Coding "Training Institution"
* trainingInstitution from https://litlfred.github.io/ihris/dak/ValueSet/training_institution (extensible)
* inCadre 0..1 Coding "Cadre"
* inCadre from https://litlfred.github.io/ihris/dak/ValueSet/cadre (extensible)
* outCountry 0..1 Coding "Country Trained in"
* outCountry from https://litlfred.github.io/ihris/dak/ValueSet/country (extensible)
* outInstitution 0..1 string "Training Institution"
* outCadre 0..1 Coding "Cadre"
* outCadre from https://litlfred.github.io/ihris/dak/ValueSet/cadre (extensible)

Mapping: Training-I2CE
Id: i2ce
Source: Training
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Training"
* -> "iHRIS_Training"
* indexNum -> "index_num"
* cadre -> "cadre"
* intakeDate -> "intake_date"
* graduation -> "graduation"
* trainedOutside -> "trained_outside"
* trainingProgram -> "training_program"
* trainingInstitution -> "training_institution"
* inCadre -> "in_cadre"
* outCountry -> "out_country"
* outInstitution -> "out_institution"
* outCadre -> "out_cadre"
