// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/TrainingDisrupt.json. Do not edit: change the source or the generator.

Logical: TrainingDisrupt
Id: TrainingDisrupt
Title: "Training Disruption"
Description: "The iHRIS 4.3.3 form class `iHRIS_TrainingDisrupt` (forms: training_disrupt; extends `I2CE_Form`), as a logical model. Derived from ihris-qualify/form-class/iHRIS_TrainingDisrupt."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/TrainingDisrupt"
* ^version = "4.3.3"
* ^status = #draft
* disruptionReason 1..1 Coding "Disruption Reason"
* disruptionReason from https://litlfred.github.io/ihris/dak/ValueSet/training_disruption_reason (extensible)
* disruptionDate 1..1 date "Disruption Date"
* resumptionDate 0..1 date "Resumption Date"

Mapping: TrainingDisrupt-I2CE
Id: i2ce
Source: TrainingDisrupt
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_TrainingDisrupt"
* -> "iHRIS_TrainingDisrupt"
* disruptionReason -> "disruption_reason"
* disruptionDate -> "disruption_date"
* resumptionDate -> "resumption_date"
