// GENERATED by src/tools/gen_fsh.py from src/ihris-data-dictionary/data-dictionary/Training_Course_Exam.json. Do not edit: change the source or the generator.

Logical: Training_Course_Exam
Id: Training-Course-Exam
Title: "Training Course Exam"
Description: "The iHRIS 4.3.3 form class `iHRIS_Training_Course_Exam` (forms: training_course_exam; extends `I2CE_Form`), as a logical model. Derived from ihris-common/form-class/iHRIS_Training_Course_Exam."
* ^url = "https://litlfred.github.io/ihris/dak/StructureDefinition/Training_Course_Exam"
* ^version = "4.3.3"
* ^status = #draft
* notes 0..1 string "Notes"
* evaluationDate 1..1 date "Evaluation Date"
* trainingCourseExamType 1..1 Coding "Exam Type"
* trainingCourseExamType from https://litlfred.github.io/ihris/dak/ValueSet/training_course_exam_type (extensible)
* score 1..1 integer "Score"

Mapping: Training_Course_Exam-I2CE
Id: i2ce
Source: Training_Course_Exam
Target: "https://launchpad.net/i2ce"
Title: "I2CE form class iHRIS_Training_Course_Exam"
* -> "iHRIS_Training_Course_Exam"
* notes -> "notes"
* evaluationDate -> "evaluation_date"
* trainingCourseExamType -> "training_course_exam_type"
* score -> "score"
