#!/usr/bin/env python3
"""Generate the FHIR Shorthand of src/ihris-4-on-fhir from the derived data dictionary and terminology.

  python3 src/tools/gen_fsh.py            # write src/ihris-4-on-fhir/input/fsh/
  python3 src/tools/gen_fsh.py --check    # fail if the committed FSH is stale
  python3 src/tools/gen_fsh.py --sushi    # also run SUSHI and prove the build equals the JSON (D8)

Design: docs/design/fhir-strategy.md (D2: Python generates FSH, SUSHI is the build; D8: the terminology JSON stays
until the SUSHI build of the same content is equal to it). Skill `ihris-4-on-fhir`.

F2, TERMINOLOGY. Each CodeSystem, ValueSet and ConceptMap in src/ihris-data-dictionary/terminology/ becomes one FSH
`Instance` (`Usage: #definition`) that assigns every element the JSON holds and nothing else, so the build is the same
resource: `--sushi` compares SUSHI's output with the JSON, element by element, and fails on any difference.

Nothing here writes a value the source does not hold (AGENTS.md section 7).
"""
import glob
import json
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
IG = os.path.join(ROOT, "src", "ihris-4-on-fhir")
FSH = os.path.join(IG, "input", "fsh")
TERMINOLOGY = os.path.join(ROOT, "src", "ihris-data-dictionary", "terminology")
HEADER = "// GENERATED by src/tools/gen_fsh.py from {src}. Do not edit: change the source or the generator.\n"

# Elements of type `code` (FSH writes these as #code, never as a string), by path with indexes removed.
CODES = {
    "status", "content", "property.type", "property.code", "concept.code", "concept.property.code",
    "compose.include.concept.code", "group.element.code", "group.element.target.code",
    "group.element.target.equivalence", "concept.property.valueCoding.code",
}


def fsh_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fsh_code(s):
    # The quoted form takes any code: spaces, '#', and characters FSH would otherwise read as syntax.
    return "#" + (s if re.fullmatch(r"[A-Za-z0-9_.\-]+", s) else fsh_string(s))


def fsh_value(path, v):
    bare = re.sub(r"\[\d+\]", "", path)
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if bare in CODES:
        return fsh_code(v)
    return fsh_string(v)


def rules(obj, path=""):
    """Every leaf of `obj` as an FSH assignment rule, in the JSON's own order."""
    out = []
    for k, v in obj.items():
        if path == "" and k in ("resourceType", "id"):
            continue  # the Instance's name and InstanceOf say these
        p = f"{path}.{k}" if path else k
        if isinstance(v, dict):
            out += rules(v, p)  # a Coding too: one rule per element keeps the JSON's own key order in SUSHI's build
        elif isinstance(v, list):
            for i, x in enumerate(v):
                out += rules(x, f"{p}[{i}]") if isinstance(x, dict) else [f"* {p}[{i}] = {fsh_value(p, x)}"]
        else:
            out.append(f"* {p} = {fsh_value(p, v)}")
    return out


def instance_fsh(res, src):
    # Named <Type>-<id>: a CodeSystem and its ValueSet often share an id, which FHIR allows across types and FSH does
    # not allow across Instance names. The id is then assigned explicitly.
    head = [HEADER.format(src=src), f"Instance: {res['resourceType']}-{res['id']}", f"InstanceOf: {res['resourceType']}",
            "Usage: #definition", f"* id = {fsh_string(res['id'])}"]
    # No Title:/Description: keywords: the rules assign both, in the JSON's own order, which SUSHI keeps.
    return "\n".join(head + rules(res)) + "\n"


# Where SUSHI writes, and how a built terminology resource is named in src/ihris-data-dictionary/terminology/:
# `<type>-<last segment of its url>.json`, the names build_dak.py always gave them.
BUILT = os.path.join(IG, "fsh-generated", "resources")
DD = os.path.join(ROOT, "src", "ihris-data-dictionary", "data-dictionary")
TERM_FSH = os.path.join(FSH, "terminology")
LM_FSH = os.path.join(FSH, "logical-models")


def json_name(res):
    return f"{res['resourceType']}-{res['url'].rsplit('/', 1)[1]}.json"


def clear_terminology():
    """build_dak.py calls this before writing the terminology afresh."""
    if os.path.isdir(TERM_FSH):
        shutil.rmtree(TERM_FSH)
    os.makedirs(TERM_FSH, exist_ok=True)


def write_terminology(res, src="src/tools/build_dak.py"):
    """build_dak.py's terminology writer since the D8 switch: one FSH Instance per resource. The JSON is SUSHI's."""
    os.makedirs(TERM_FSH, exist_ok=True)
    with open(os.path.join(TERM_FSH, f"{res['resourceType']}-{res['id']}.fsh"), "w", encoding="utf-8") as f:
        f.write(instance_fsh(res, src))


# F3, LOGICAL MODELS. The FHIR R4 type of each I2CE field type. A choice, stated once (fhir-strategy.md F3):
# CURRENCY holds an amount and a currency, which is Money; INT_GENERATE is a generated record number, an Identifier.
I2CE_TYPE = {
    "DATE_YMD": "date", "DATE_YM": "date", "DATE_Y": "date",
    "STRING_LINE": "string", "STRING_MLINE": "string", "STRING_TEXT": "string",
    "YESNO": "boolean", "BOOL": "boolean",
    "INT": "integer", "PERCENT_INT": "integer", "CURRENCY": "Money", "INT_GENERATE": "Identifier",
    "MAP": "Coding", "ENUM": "Coding", "MAP_MULT": "Coding",
    "DOCUMENT": "Attachment", "IMAGE": "Attachment",
}


def logical_fsh(d, src):
    """One data-dictionary sheet as an FSH Logical. Carries only what the sheet states: the field, its label (short),
    its type and cardinality, its value set, and a definition only where a person authored one."""
    lm_id = d["logicalModel"].rsplit("/", 1)[1].replace("_", "-")
    lines = [HEADER.format(src=src), f"Logical: {d['group']}", f"Id: {lm_id}", f"Title: {fsh_string(d['title'])}",
             "Description: " + fsh_string(f"The iHRIS {RELEASE} form class `{d['class']}` (forms: {', '.join(d['forms'])}; "
                                          f"extends `{d['extends']}`), as a logical model. Derived from {', '.join(d['sources'])}."),
             f"* ^url = {fsh_string(d['logicalModel'])}", f"* ^version = {fsh_string(RELEASE)}", "* ^status = #draft"]
    mapping = [f"Mapping: {d['group']}-I2CE", f"Id: i2ce", f"Source: {d['group']}", f"Target: {fsh_string('https://launchpad.net/i2ce')}",
               f"Title: {fsh_string('I2CE form class ' + d['class'])}",
               f"* -> {fsh_string(d['class'])}"]
    for e in d["elements"]:
        field = e["id"].rsplit(".", 1)[1]
        # FHIR element names are plain alphanumerics (eld-20): the I2CE field `start_date` is the element `startDate`,
        # and the Mapping below keeps the source field's own name.
        name = re.sub(r"_+([A-Za-z0-9])", lambda m: m.group(1).upper(), field)
        mapping.append(f"* {name} -> {fsh_string(field)}")
        i2ce = (e.get("source") or {}).get("i2ceType")
        typ = I2CE_TYPE.get(i2ce)
        if typ is None:
            raise SystemExit(f"gen_fsh: {e['id']}: no FHIR type for I2CE type {i2ce!r}; add it to I2CE_TYPE")
        lo = "1" if e["optionality"] == "R" else "0"
        hi = "*" if i2ce == "MAP_MULT" or e.get("duplicates") == "Yes" else "1"
        rule = f"* {name} {lo}..{hi} {typ} {fsh_string(e['dataElementLabel'])}"
        if e.get("description") and e.get("descriptionStatus") != "to-author":
            rule += f" {fsh_string(e['description'])}"
        lines.append(rule)
        for vs in e.get("inputOptions") or []:
            if typ == "Coding":
                # extensible: an iHRIS deployment adds codes to its lists (fhir-strategy.md F3, for the owner to review)
                lines.append(f"* {name} from {vs} (extensible)")
    return "\n".join(lines) + "\n\n" + "\n".join(mapping) + "\n"


RELEASE = "4.3.3"


def logical_models():
    """{relative fsh path: text}, one per data-dictionary sheet."""
    out = {}
    for f in sorted(glob.glob(os.path.join(DD, "*.json"))):
        d = json.load(open(f, encoding="utf-8"))
        out[f"logical-models/{d['group']}.fsh"] = logical_fsh(d, os.path.relpath(f, ROOT))
    return out


def write_logical(files):
    if os.path.isdir(LM_FSH):
        shutil.rmtree(LM_FSH)
    for rel, text in files.items():
        p = os.path.join(FSH, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        open(p, "w", encoding="utf-8").write(text)


def stale_logical(files):
    have = {os.path.relpath(p, FSH): open(p, encoding="utf-8").read() for p in glob.glob(os.path.join(LM_FSH, "*.fsh"))}
    return sorted(set(have) ^ set(files)) + sorted(k for k in files if k in have and have[k] != files[k])


def sushi():
    """Run SUSHI over the IG; fail unless it reports 0 errors and 0 warnings (fhir-strategy.md, F1)."""
    r = subprocess.run(["sushi", "build", IG], capture_output=True, text=True)
    text = r.stdout + r.stderr
    m = re.search(r"(\d+) Errors?\s.*?(\d+) Warnings?", text, re.S)
    errors, warnings = (int(m.group(1)), int(m.group(2))) if m else (None, None)
    # SUSHI loads three helper packages (hl7.fhir.uv.tools.r4, hl7.terminology.r4, hl7.fhir.uv.extensions.r4) by
    # itself. Where the package registry is unreachable each one is a warning about the network, not about this FSH:
    # reported as COULD NOT DETERMINE outside CI, and an error in CI, where the registry is reachable.
    offline = len(re.findall(r"Failed to load automatically-provided", text))
    if offline and not os.environ.get("CI") and warnings is not None and warnings == offline:
        print(f"gen_fsh: WARNING could not determine full cleanliness: {offline} automatically-provided package(s) "
              "did not load (package registry unreachable); SUSHI reported no other warning")
        warnings = 0
    if r.returncode != 0 or errors != 0 or warnings != 0:
        sys.stderr.write(text[-4000:])
        raise SystemExit(f"gen_fsh: SUSHI is not clean (errors={errors}, warnings={warnings}, exit={r.returncode})")
    print(f"gen_fsh: SUSHI clean (0 errors, 0 warnings)")


def built_terminology():
    """{terminology JSON file name: resource} as SUSHI built them."""
    out = {}
    for p in glob.glob(os.path.join(BUILT, "*.json")):
        res = json.load(open(p, encoding="utf-8"))
        if res.get("resourceType") in ("CodeSystem", "ValueSet", "ConceptMap"):
            out[json_name(res)] = res
    return out


def dump(res):
    return json.dumps(res, indent=2, ensure_ascii=False) + "\n"


def write_terminology_json(built):
    """The terminology JSON every reader uses (site, glossary, validate_fhir.py) is SUSHI's output (D8)."""
    for f in glob.glob(os.path.join(TERMINOLOGY, "*.json")):
        os.remove(f)
    for name, res in built.items():
        open(os.path.join(TERMINOLOGY, name), "w", encoding="utf-8").write(dump(res))
    print(f"gen_fsh: {len(built)} terminology resource(s) written from the SUSHI build to {os.path.relpath(TERMINOLOGY, ROOT)}")


def terminology_diffs(built):
    """D8, the standing check: the committed terminology JSON is exactly what SUSHI builds from the FSH."""
    have = {os.path.basename(p): open(p, encoding="utf-8").read() for p in glob.glob(os.path.join(TERMINOLOGY, "*.json"))}
    want = {n: dump(r) for n, r in built.items()}
    return [f"{n}: in the SUSHI build, not committed" for n in sorted(set(want) - set(have))] + \
           [f"{n}: committed, not in the SUSHI build" for n in sorted(set(have) - set(want))] + \
           [f"{n}: differs from the SUSHI build" for n in sorted(set(want) & set(have)) if want[n] != have[n]]


def main():
    lm = logical_models()
    if "--check" in sys.argv:
        bad = stale_logical(lm)
        if bad:
            raise SystemExit("gen_fsh: logical-model FSH is STALE: " + ", ".join(bad[:10]))
        sushi()
        diffs = terminology_diffs(built_terminology())
        if diffs:
            raise SystemExit("gen_fsh: the terminology JSON is not the SUSHI build (D8):\n  " + "\n  ".join(diffs[:20]))
        print(f"gen_fsh: OK ({len(lm)} logical models; the terminology JSON is the SUSHI build)")
        return
    write_logical(lm)
    print(f"gen_fsh: {len(lm)} logical model(s) in {os.path.relpath(LM_FSH, ROOT)}")
    sushi()
    write_terminology_json(built_terminology())


if __name__ == "__main__":
    main()
